package my.com.cmg.iwp.maintenance.model;

// Generated Apr 6, 2012 10:02:52 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * AtcDetail generated by hbm2java
 */
@Entity
@Table(name = "t_atc_details", uniqueConstraints = @UniqueConstraint(columnNames = "atc_code"))
public class AtcDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long atcSeqno = Long.MIN_VALUE;
	private int atcLevel;
	private String atcCode;
	private String atcContent;
	private String atcStatus;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private List<Drug> drugList;
	private Set<GenericNameAtc> genericNameAtcs = new HashSet<GenericNameAtc>(0);

	public AtcDetail() {
	}

	public AtcDetail(long atcSeqno, String atcCode, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.atcSeqno = atcSeqno;

		this.atcCode = atcCode;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "atc_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "atcSEQ", sequenceName = "t_atc_details_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "atcSEQ")
	public long getAtcSeqno() {
		return this.atcSeqno;
	}

	public void setAtcSeqno(long atcSeqno) {
		this.atcSeqno = atcSeqno;
	}

	@Column(name = "atc_level")
	public int getAtcLevel() {
		return atcLevel;
	}

	public void setAtcLevel(int atcLevel) {
		this.atcLevel = atcLevel;
	}

	@Column(name = "atc_code", nullable = false, length = 15)
	public String getAtcCode() {
		return this.atcCode;
	}

	public void setAtcCode(String atcCode) {
		this.atcCode = atcCode;
	}

	@Column(name = "atc_content", length = 350)
	public String getAtcContent() {
		return atcContent;
	}

	public void setAtcContent(String atcContent) {
		this.atcContent = atcContent;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by")
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public void setDrugList(List<Drug> drugList) {
		this.drugList = drugList;
	}

	@Transient
	public List<Drug> getDrugList() {
		return drugList;
	}

	public void setGenericNameAtcs(Set<GenericNameAtc> genericNameAtcs) {
		this.genericNameAtcs = genericNameAtcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genericName")
	public Set<GenericNameAtc> getGenericNameAtcs() {
		return genericNameAtcs;
	}

	public void setAtcStatus(String atcStatus) {
		this.atcStatus = atcStatus;
	}

	@Column(name = "atc_status", length = 10)
	public String getAtcStatus() {
		return atcStatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((atcCode == null) ? 0 : atcCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AtcDetail other = (AtcDetail) obj;
		if (atcCode == null) {
			if (other.atcCode != null)
				return false;
		} else if (!atcCode.equals(other.atcCode))
			return false;
		return true;
	}
}