package my.com.cmg.iwp.backend.model.integration.spub;

// default package
// Generated Nov 5, 2012 10:47:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PhSpubDiagnosisInt generated by hbm2java
 */
@Entity
@Table(name = "t_spub_diagnosis_int")
@XmlRootElement(name = "SpubDiagnosisInt")
@JsonIgnoreProperties(ignoreUnknown=true)
public class SpubDiagnosisInt implements java.io.Serializable {

	private long spubDiagnosisSeqno;
	private Integer version;
	private SpubHdrsInt spubHdrsInt;
	private String hospitalId;
	private String codingMethod;
	private String diagnosisCode;
	private String description;
	private Date diagnosisDate;
	private String diagnosisType;
	private Long createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;

	public SpubDiagnosisInt() {
	}

	public SpubDiagnosisInt(long spubDiagnosisSeqno, SpubHdrsInt spubHdrsInt) {
		this.spubDiagnosisSeqno = spubDiagnosisSeqno;
		this.spubHdrsInt = spubHdrsInt;
	}

	public SpubDiagnosisInt(long spubDiagnosisSeqno, SpubHdrsInt spubHdrsInt,
			String hospitalId, String codingMethod, String diagnosisCode,
			String description, Date diagnosisDate, String diagnosisType,
			Long createdBy, Date createdDate, Long updatedBy, Date updatedDate) {
		this.spubDiagnosisSeqno = spubDiagnosisSeqno;
		this.spubHdrsInt = spubHdrsInt;
		this.hospitalId = hospitalId;
		this.codingMethod = codingMethod;
		this.diagnosisCode = diagnosisCode;
		this.description = description;
		this.diagnosisDate = diagnosisDate;
		this.diagnosisType = diagnosisType;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "spub_diagnosis_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "spub_diagnosis_seqno", sequenceName = "t_spub_diagnosis_int_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "spub_diagnosis_seqno")
	@JsonIgnore
	public long getSpubDiagnosisSeqno() {
		return this.spubDiagnosisSeqno;
	}

	public void setSpubDiagnosisSeqno(long spubDiagnosisSeqno) {
		this.spubDiagnosisSeqno = spubDiagnosisSeqno;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne
	@JoinColumn(name = "spub_hdr_seqno", nullable = false)
	@JsonBackReference("SpubDiagnosisInt")
	public SpubHdrsInt getSpubHdrsInt() {
		return this.spubHdrsInt;
	}

	public void setSpubHdrsInt(SpubHdrsInt spubHdrsInt) {
		this.spubHdrsInt = spubHdrsInt;
	}

	@Column(name = "hospital_id", length = 50)
	public String getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId;
	}

	@Column(name = "coding_method")
	public String getCodingMethod() {
		return this.codingMethod;
	}

	public void setCodingMethod(String codingMethod) {
		this.codingMethod = codingMethod;
	}

	@Column(name = "diagnosis_code", length = 8)
	public String getDiagnosisCode() {
		return this.diagnosisCode;
	}

	public void setDiagnosisCode(String diagnosisCode) {
		this.diagnosisCode = diagnosisCode;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "diagnosis_date", length = 13)
	public Date getDiagnosisDate() {
		return this.diagnosisDate;
	}

	public void setDiagnosisDate(Date diagnosisDate) {
		this.diagnosisDate = diagnosisDate;
	}

	@Column(name = "diagnosis_type", length = 2)
	public String getDiagnosisType() {
		return this.diagnosisType;
	}

	public void setDiagnosisType(String diagnosisType) {
		this.diagnosisType = diagnosisType;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ (int) (spubDiagnosisSeqno ^ (spubDiagnosisSeqno >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SpubDiagnosisInt other = (SpubDiagnosisInt) obj;
		if (spubDiagnosisSeqno != other.spubDiagnosisSeqno)
			return false;
		return true;
	}

}
