package my.com.cmg.iwp.maintenance.model.report.stg;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhBudgetMovementStg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_budget_movement_stg")
public class BudgetMovementStg implements java.io.Serializable {

	private long budgetmSeqno;
	private String voteCode;
	private String voteDescription;
	private String voteObjectCode;
	private Double pendingAmt;
	private Double liabilityAmt;
	private Double utilizedAmt;
	private Double actualBalance;
	private long createdBy;
	private String sessionId;
	private Date updatedDate;
	private String transactionType;
	private String transactionNumber;
	private Double transactionAmt;
	private Date createdDate;
	private String clinicName;
	private String budgetType;
	private String lpoNo;
	private String nePVote;
	
	public BudgetMovementStg() {
	}

	public BudgetMovementStg(long budgetmSeqno, long createdBy) {
		this.budgetmSeqno = budgetmSeqno;
		this.createdBy = createdBy;
	}

	public BudgetMovementStg(long budgetmSeqno, String voteCode,
			String voteDescription, String voteObjectCode,
			Double pendingAmt, Double liabilityAmt,
			Double utilizedAmt, Double actualBalance, long createdBy,
			String sessionId,Date updatedDate, String transactionType) {
		this.budgetmSeqno = budgetmSeqno;
		this.voteCode = voteCode;
		this.voteDescription = voteDescription;
		this.voteObjectCode = voteObjectCode;
		this.pendingAmt = pendingAmt;
		this.liabilityAmt = liabilityAmt;
		this.utilizedAmt = utilizedAmt;
		this.actualBalance = actualBalance;
		this.createdBy = createdBy;
		this.sessionId = sessionId;
		this.updatedDate = updatedDate;
		this.transactionType = transactionType;
	}

	@Id
	@Column(name = "budgetm_seqno", unique = true, nullable = false)
	public long getBudgetmSeqno() {
		return this.budgetmSeqno;
	}

	public void setBudgetmSeqno(long budgetmSeqno) {
		this.budgetmSeqno = budgetmSeqno;
	}

	@Column(name = "vote_code", length = 33)
	public String getVoteCode() {
		return this.voteCode;
	}

	public void setVoteCode(String voteCode) {
		this.voteCode = voteCode;
	}

	@Column(name = "vote_description", length = 50)
	public String getVoteDescription() {
		return this.voteDescription;
	}

	public void setVoteDescription(String voteDescription) {
		this.voteDescription = voteDescription;
	}

	@Column(name = "vote_object_code", length = 6)
	public String getVoteObjectCode() {
		return this.voteObjectCode;
	}

	public void setVoteObjectCode(String voteObjectCode) {
		this.voteObjectCode = voteObjectCode;
	}

	@Column(name = "pending_amt", precision = 15, scale = 4)
	public Double getPendingAmt() {
		return this.pendingAmt;
	}

	public void setPendingAmt(Double pendingAmt) {
		this.pendingAmt = pendingAmt;
	}

	@Column(name = "liability_amt", precision = 15, scale = 4)
	public Double getLiabilityAmt() {
		return this.liabilityAmt;
	}

	public void setLiabilityAmt(Double liabilityAmt) {
		this.liabilityAmt = liabilityAmt;
	}

	@Column(name = "utilized_amt", precision = 15, scale = 4)
	public Double getUtilizedAmt() {
		return this.utilizedAmt;
	}

	public void setUtilizedAmt(Double utilizedAmt) {
		this.utilizedAmt = utilizedAmt;
	}

	@Column(name = "actual_balance", precision = 15, scale = 4)
	public Double getActualBalance() {
		return this.actualBalance;
	}

	public void setActualBalance(Double actualBalance) {
		this.actualBalance = actualBalance;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "session_id", length = 50)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "transaction_type", length = 200)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}
	
	@Column(name = "transaction_number", length = 20)
	public String getTransactionNumber() {
		return transactionNumber;
	}

	public void setTransactionNumber(String transactionNumber) {
		this.transactionNumber = transactionNumber;
	}
	
	@Column(name = "transaction_amt", nullable = false, precision = 15)
	public Double getTransactionAmt() {
		return transactionAmt;
	}

	public void setTransactionAmt(Double transactionAmt) {
		this.transactionAmt = transactionAmt;
	}

	@Column(name = "created_date",length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name="clinic_name")
	public String getClinicName() {
		return clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}

	@Column(name="budget_type")
	public String getBudgetType() {
		return budgetType;
	}

	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}

	@Column(name="lpo_no")
	public String getLpoNo() {
		return lpoNo;
	}

	public void setLpoNo(String lpoNo) {
		this.lpoNo = lpoNo;
	}

	@Column(name = "nep_vote")
	public String getNePVote() {
		return nePVote;
	}

	public void setNePVote(String nePVote) {
		this.nePVote = nePVote;
	}
}
