package my.com.cmg.iwp.maintenance.model;

// Generated Jul 9, 2012 4:26:24 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "t_brands", uniqueConstraints = @UniqueConstraint(columnNames = { "brd_code" }))
@JsonIgnoreProperties(ignoreUnknown=true)
public class Brand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2497211717349043126L;
	private long brdSeqno = Long.MIN_VALUE;
	private String brdCode;
	private String brdName;
	private String brdRemarks;
	private String brdStatus;
	private Character activeFlag = 'A';
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private long updatedBy;
	private Date updatedDate;
	private Date createdDate;
	private Character brandType;
//	private Set<Item> items;
	private Set<ItemBrand> itemBrands;

	public Brand() {
	}

	public Brand(long brdSeqno, long createdBy, long updatedBy,
			Date updatedDate, Date createdDate) {
		this.brdSeqno = brdSeqno;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.createdDate = createdDate;
	}

	public Brand(long brdSeqno, String brdCode, String brdName,
			String brdRemarks, String brdStatus, Character activeFlag,
			String parameter1, String parameter2, BigDecimal parameter3,
			BigDecimal parameter4, long createdBy, long updatedBy,
			Date updatedDate, Date createdDate) {
		this.brdSeqno = brdSeqno;
		this.brdCode = brdCode;
		this.brdName = brdName;
		this.brdRemarks = brdRemarks;
		this.brdStatus = brdStatus;
		this.activeFlag = activeFlag;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.createdDate = createdDate;
	}

	@Id
	@Column(name = "brd_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "brd_seqno", sequenceName = "t_brands_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "brd_seqno")
	public long getBrdSeqno() {
		return this.brdSeqno;
	}

	public void setBrdSeqno(long brdSeqno) {
		this.brdSeqno = brdSeqno;
	}

	@Column(name = "brd_code", nullable = false, length = 10)
	public String getBrdCode() {
		return this.brdCode;
	}

	public void setBrdCode(String brdCode) {
		this.brdCode = brdCode;
	}

	@Column(name = "brd_name", nullable = false, length = 20)
	public String getBrdName() {
		return this.brdName;
	}

	public void setBrdName(String brdName) {
		this.brdName = brdName;
	}

	@Column(name = "brd_remarks", length = 100)
	public String getBrdRemarks() {
		return this.brdRemarks;
	}

	public void setBrdRemarks(String brdRemarks) {
		this.brdRemarks = brdRemarks;
	}

	@Column(name = "brd_status", length = 10)
	public String getBrdStatus() {
		return this.brdStatus;
	}

	public void setBrdStatus(String brdStatus) {
		this.brdStatus = brdStatus;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column(name = "brand_type", nullable = false, length = 1)
	public Character getBrandType() {
		return brandType;
	}

	public void setBrandType(Character brandType) {
		this.brandType = brandType;
	}

	/*@ManyToMany(fetch = FetchType.LAZY, mappedBy = "brands")
	public Set<Item> getItems() {
		return items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}
*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<ItemBrand> getItemBrands() {
		return itemBrands;
	}

	public void setItemBrands(Set<ItemBrand> itemBrands) {
		this.itemBrands = itemBrands;
	}
}