package my.com.cmg.iwp.backend.model.integration;
// default package
// Generated May 23, 2013 12:39:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;


/**
 * PhDispenseReasonsInt generated by hbm2java
 */
@Entity
@Table(name = "t_dispense_reasons_int")
@JsonIgnoreProperties(ignoreUnknown=true)
public class DispenseReasonsInt implements java.io.Serializable {

	private long reasonIntSeqno;
	private Character stage;
	private String reasonCode;
	private String drugCode;
	private String remark;

	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private OutsourceOrderInt outsourceOrderInt;

	public DispenseReasonsInt() {
	}

	public DispenseReasonsInt(long reasonIntSeqno, OutsourceOrderInt outsourceOrderInt,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.reasonIntSeqno = reasonIntSeqno;
		this.outsourceOrderInt = outsourceOrderInt;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public DispenseReasonsInt(long reasonIntSeqno, Character stage,
			String reasonCode, String remark, OutsourceOrderInt outsourceOrderInt,
			String parameter1, String parameter2, BigDecimal parameter3,
			BigDecimal parameter4, Date parameter5, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.reasonIntSeqno = reasonIntSeqno;
		this.stage = stage;
		this.reasonCode = reasonCode;
		this.remark = remark;
		this.outsourceOrderInt = outsourceOrderInt;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@SequenceGenerator(name="ph_dispense_reasons_int_seq", sequenceName="t_dispense_reasons_int_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ph_dispense_reasons_int_seq")
	@Column(name = "reason_int_seqno", nullable = false)
	@JsonIgnore
	public long getReasonIntSeqno() {
		return this.reasonIntSeqno;
	}

	public void setReasonIntSeqno(long reasonIntSeqno) {
		this.reasonIntSeqno = reasonIntSeqno;
	}

	@Column(name = "stage", length = 1)
	public Character getStage() {
		return this.stage;
	}

	public void setStage(Character stage) {
		this.stage = stage;
	}

	@Column(name = "reason_code", unique = true, length = 20)
	public String getReasonCode() {
		return this.reasonCode;
	}

	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode;
	}

	@Column(name = "remark", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}


	@ManyToOne
	@JoinColumn(name = "outsource_int_seqno", nullable = false)
	@JsonBackReference("DispenseReasonsOutsourceOrderInt")
	public OutsourceOrderInt getOutsourceOrderInt() {
		return this.outsourceOrderInt;
	}

	public void setOutsourceOrderInt(OutsourceOrderInt outsourceOrderInt) {
		this.outsourceOrderInt = outsourceOrderInt;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "drug_code",  length = 20)
	public String getDrugCode() {
	    return drugCode;
	}

	public void setDrugCode(String drugCode) {
	    this.drugCode = drugCode;
	}
	
}
