package my.com.cmg.iwp.maintenance.model;

// Generated Jul 16, 2012 5:39:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Indication generated by hbm2java
 */
@Entity
@Table(name = "t_indications", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Indication implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4108046849037816561L;
	private long indicationSeqno = Long.MIN_VALUE;
	private String code;
	private String fukkmDesc;
	private String indicationDesc;
	private String indicationLocal;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	public Indication() {
	}

	public Indication(long indicationSeqno, String code, String fukkmDesc,
			String indicationDesc, String indicationLocal, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.indicationSeqno = indicationSeqno;
		this.code = code;
		this.fukkmDesc = fukkmDesc;
		this.indicationDesc = indicationDesc;
		this.indicationLocal = indicationLocal;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public Indication(long indicationSeqno, String code, String fukkmDesc,
			String indicationDesc, String indicationLocal, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, Character activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.indicationSeqno = indicationSeqno;
		this.code = code;
		this.fukkmDesc = fukkmDesc;
		this.indicationDesc = indicationDesc;
		this.indicationLocal = indicationLocal;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "indication_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "indication_seqno", sequenceName = "t_indications_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "indication_seqno")
	public long getIndicationSeqno() {
		return this.indicationSeqno;
	}

	public void setIndicationSeqno(long indicationSeqno) {
		this.indicationSeqno = indicationSeqno;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "fukkm_desc", nullable = false, length = 400)
	public String getFukkmDesc() {
		return fukkmDesc;
	}

	public void setFukkmDesc(String fukkmDesc) {
		this.fukkmDesc = fukkmDesc;
	}

	@Column(name = "indication_desc", nullable = false, length = 100)
	public String getIndicationDesc() {
		return this.indicationDesc;
	}

	public void setIndicationDesc(String indicationDesc) {
		this.indicationDesc = indicationDesc;
	}

	@Column(name = "indication_local", nullable = false, length = 100)
	public String getIndicationLocal() {
		return indicationLocal;
	}

	public void setIndicationLocal(String indicationLocal) {
		this.indicationLocal = indicationLocal;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
