package my.com.cmg.iwp.maintenance.model;

// Generated Apr 6, 2012 10:02:52 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Uom generated by hbm2java
 */
@Entity
@Table(name = "t_uoms", uniqueConstraints = @UniqueConstraint(columnNames = "uom_abbreviation"))
public class Uom implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long uomSeqno = Long.MIN_VALUE;
	private String uomAbbreviation;
	private String uomDesc;
	private String uomLocalDesc;
	private String unitType;
	private String uomStatus;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	// private Set<DrugUom> drugUOMs = new HashSet<DrugUom>(0);
	// private Set<DrugDuration> drugDurations = new HashSet<DrugDuration>(0);

	public Uom() {
	}

	public Uom(long uomSeqno, String uomDesc, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate) {
		this.uomSeqno = uomSeqno;

		this.uomDesc = uomDesc;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "uom_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "uomSEQ", sequenceName = "t_uoms_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "uomSEQ")
	public long getUomSeqno() {
		return this.uomSeqno;
	}

	public void setUomSeqno(long uomSeqno) {
		this.uomSeqno = uomSeqno;
	}

	@Column(name = "uom_abbreviation", nullable = false, length = 10)
	public String getUomAbbreviation() {
		return uomAbbreviation;
	}

	public void setUomAbbreviation(String uomAbbreviation) {
		this.uomAbbreviation = uomAbbreviation;
	}

	@Column(name = "uom_desc", nullable = false, length = 40)
	public String getUomDesc() {
		return this.uomDesc;
	}

	public void setUomDesc(String uomDesc) {
		this.uomDesc = uomDesc;
	}
	
	@Column(name = "uom_local_desc", nullable = false, length = 40)
	public String getUomLocalDesc() {
		return uomLocalDesc;
	}

	public void setUomLocalDesc(String uomLocalDesc) {
		this.uomLocalDesc = uomLocalDesc;
	}

	@Column(name = "unit_type", length = 40)
	public String getUnitType() {
		return unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	@Column(name = "uom_status", length = 1)
	public String getUomStatus() {
		return uomStatus;
	}

	public void setUomStatus(String uomStatus) {
		this.uomStatus = uomStatus;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by")
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/*
	 * public void setDrugUOMs(Set<DrugUom> drugUOMs) { this.drugUOMs =
	 * drugUOMs; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "uom") public Set<DrugUom>
	 * getDrugUOMs() { return drugUOMs; }
	 */
	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "doseUom") public
	 * Set<DrugDuration> getDrugDurations() { return drugDurations; }
	 * 
	 * public void setDrugDurations(Set<DrugDuration> drugDurations) {
	 * this.drugDurations = drugDurations; }
	 */

}
