package my.com.cmg.iwp.maintenance.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhBudgetMovement generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_budget_movement")
public class BudgetMovement implements java.io.Serializable {

	private Long budgetMovementSeqno;
	private String ptjCode;

	private Double pendingAmount;
	private Double liabilityAmount;
	private Double utilisedAmount;
	private Double balance;
	private Character activeFl;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;
	private String transactionType;
	private String transactionNumber;
	private Long voteSeqno;
	private String facilityCode;
	private Double transactionAmount;
	private String warrantType;
	private String budgetType;
	private String financialYear;
	private CBMaster cbMaster;

	

	@Id
	@Column(name = "budget_movement_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "ph_budget_movement_seq_hq", sequenceName = "t_budget_movement_seq", allocationSize = 1)
	@GeneratedValue(generator = "ph_budget_movement_seq_hq")
	public Long getBudgetMovementSeqno() {
		return budgetMovementSeqno;
	}

	public void setBudgetMovementSeqno(Long budgetMovementSeqno) {
		this.budgetMovementSeqno = budgetMovementSeqno;
	}

	@Column(name = "facility_code")
	public String getFacilityCode() {
		return facilityCode;
	}

	public void setFacilityCode(String facilityCode) {
		this.facilityCode = facilityCode;
	}

	@Column(name = "pending_amount", nullable = false, precision = 16, scale = 4)
	public Double getPendingAmount() {
		return this.pendingAmount;
	}

	public void setPendingAmount(Double pendingAmount) {
		this.pendingAmount = pendingAmount;
	}

	@Column(name = "liability_amount", nullable = false, precision = 16, scale = 4)
	public Double getLiabilityAmount() {
		return this.liabilityAmount;
	}

	public void setLiabilityAmount(Double liabilityAmount) {
		this.liabilityAmount = liabilityAmount;
	}

	@Column(name = "utilised_amount", nullable = false, precision = 16, scale = 4)
	public Double getUtilisedAmount() {
		return this.utilisedAmount;
	}

	public void setUtilisedAmount(Double utilisedAmount) {
		this.utilisedAmount = utilisedAmount;
	}

	@Column(name = "balance", nullable = false, precision = 16, scale = 4)
	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	@Column(name = "active_flag", nullable = false, length = 1)
	public Character getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(Character activeFl) {
		this.activeFl = activeFl;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "transaction_type", nullable = false, length = 20)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "transaction_number", length = 20)
	public String getTransactionNumber() {
		return transactionNumber;
	}

	public void setTransactionNumber(String transactionNumber) {
		this.transactionNumber = transactionNumber;
	}

	@Column(name = "vote_seqno")
	public Long getVoteSeqno() {
		return voteSeqno;
	}

	public void setVoteSeqno(Long voteSeqno) {
		this.voteSeqno = voteSeqno;
	}

	@Column(name = "source_ptj_code", nullable = false, length = 20)
	public String getPtjCode() {
		return ptjCode;
	}

	public void setPtjCode(String ptjCode) {
		this.ptjCode = ptjCode;
	}

	@Column(name="transaction_amount")
	public Double getTransactionAmount() {
		return transactionAmount;
	}

	public void setTransactionAmount(Double transactionAmount) {
		this.transactionAmount = transactionAmount;
	}
	
	@Column(name = "warrant_type", length = 20)
	public String getWarrantType() {
		return warrantType;
	}

	public void setWarrantType(String warrantType) {
		this.warrantType = warrantType;
	}
	
	@Column(name = "budget_type", length = 10)
	public String getBudgetType() {
		return budgetType;
	}

	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}

	@Column(name ="financial_year")
	public String getFinancialYear() {
		return financialYear;
	}

	public void setFinancialYear(String financialYear) {
		this.financialYear = financialYear;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name ="CB_MSTR_SEQNO")
	public CBMaster getCBMaster() {
		return cbMaster;
	}

	public void setCBMaster(CBMaster cbMaster) {
		this.cbMaster = cbMaster;
	}
}
