package my.com.cmg.iwp.maintenance.model;

// Generated Nov 29, 2012 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhConstituentsReferenceRange generated by hbm2java
 */
@Entity
@Table(name = "T_CONSTITUENTS_REF_RANGE")
public class ConstituentsReferenceRange implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long referRgeSeqno = Long.MIN_VALUE;
	private Long pnGenerics;
	private String ageGroup;
	private BigDecimal ageFrom;
	private String ageFromUnit;
	private BigDecimal ageTo;
	private String ageToUnit;
	private BigDecimal proteinMinReferRge;
	private BigDecimal carbohydrateMinReferRge;
	private BigDecimal lipidMinReferRge;
	private BigDecimal proteinMaxReferRge;
	private BigDecimal carbohydrateMaxReferRge;
	private BigDecimal lipidMaxReferRge;
	private BigDecimal carbohydrateReferRgeUnit;
	private BigDecimal sodiumMinReferRge;
	private BigDecimal potassiumMinReferRge;
	private BigDecimal chlorideMinReferRge;
	private BigDecimal acetateMinReferRge;
	private BigDecimal phosphateMinReferRge;
	private BigDecimal magnesiumMinReferRge;
	private BigDecimal calciumMinReferRge;
	private BigDecimal sodiumMaxReferRge;
	private BigDecimal potassiumMaxReferRge;
	private BigDecimal chlorideMaxReferRge;
	private BigDecimal acetateMaxReferRge;
	private BigDecimal phosphateMaxReferRge;
	private BigDecimal magnesiumMaxReferRge;
	private BigDecimal calciumMaxReferRge;
	private BigDecimal traceElementsSolnMinReferRge;
	private BigDecimal traceElementsSolnMaxReferRge;
	private BigDecimal vitaminSolnMinReferRge;
	private BigDecimal vitaminSolnMaxReferRge;
	private BigDecimal waterSolubleMinReferRge;
	private BigDecimal waterSolubleMaxReferRge;
	private BigDecimal fatSolubleMinReferRge;
	private BigDecimal fatSolubleMaxReferRge;
	private BigDecimal glutaminMin;
	private BigDecimal glutaminMax;
	private BigDecimal glutaminAvg;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	public ConstituentsReferenceRange() {
	}

	public ConstituentsReferenceRange(long referRgeSeqno, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.referRgeSeqno = referRgeSeqno;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public ConstituentsReferenceRange(long referRgeSeqno, Long pnGenerics,
			String ageGroup, BigDecimal ageFrom, String ageFromUnit,
			BigDecimal ageTo, String ageToUnit, BigDecimal proteinMinReferRge,
			BigDecimal carbohydrateMinReferRge, BigDecimal lipidMinReferRge,
			BigDecimal proteinMaxReferRge, BigDecimal carbohydrateMaxReferRge,
			BigDecimal lipidMaxReferRge, BigDecimal carbohydrateReferRgeUnit,
			BigDecimal sodiumMinReferRge, BigDecimal potassiumMinReferRge,
			BigDecimal chlorideMinReferRge, BigDecimal acetateMinReferRge,
			BigDecimal phosphateMinReferRge, BigDecimal magnesiumMinReferRge,
			BigDecimal calciumMinReferRge, BigDecimal sodiumMaxReferRge,
			BigDecimal potassiumMaxReferRge, BigDecimal chlorideMaxReferRge,
			BigDecimal acetateMaxReferRge, BigDecimal phosphateMaxReferRge,
			BigDecimal magnesiumMaxReferRge, BigDecimal calciumMaxReferRge,
			BigDecimal traceElementsSolnMinReferRge,
			BigDecimal traceElementsSolnMaxReferRge,
			BigDecimal vitaminSolnMinReferRge,
			BigDecimal vitaminSolnMaxReferRge,
			BigDecimal waterSolubleMinReferRge,
			BigDecimal waterSolubleMaxReferRge,
			BigDecimal fatSolubleMinReferRge, BigDecimal fatSolubleMaxReferRge,
			String parameter1, String parameter2, BigDecimal parameter3,
			BigDecimal parameter4, Date parameter5, Character activeFlag,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate, BigDecimal glutaminMin, BigDecimal glutaminMax, BigDecimal glutaminAvg) {
		this.referRgeSeqno = referRgeSeqno;
		this.pnGenerics = pnGenerics;
		this.ageGroup = ageGroup;
		this.ageFrom = ageFrom;
		this.ageFromUnit = ageFromUnit;
		this.ageTo = ageTo;
		this.ageToUnit = ageToUnit;
		this.proteinMinReferRge = proteinMinReferRge;
		this.carbohydrateMinReferRge = carbohydrateMinReferRge;
		this.lipidMinReferRge = lipidMinReferRge;
		this.proteinMaxReferRge = proteinMaxReferRge;
		this.carbohydrateMaxReferRge = carbohydrateMaxReferRge;
		this.lipidMaxReferRge = lipidMaxReferRge;
		this.carbohydrateReferRgeUnit = carbohydrateReferRgeUnit;
		this.sodiumMinReferRge = sodiumMinReferRge;
		this.potassiumMinReferRge = potassiumMinReferRge;
		this.chlorideMinReferRge = chlorideMinReferRge;
		this.acetateMinReferRge = acetateMinReferRge;
		this.phosphateMinReferRge = phosphateMinReferRge;
		this.magnesiumMinReferRge = magnesiumMinReferRge;
		this.calciumMinReferRge = calciumMinReferRge;
		this.sodiumMaxReferRge = sodiumMaxReferRge;
		this.potassiumMaxReferRge = potassiumMaxReferRge;
		this.chlorideMaxReferRge = chlorideMaxReferRge;
		this.acetateMaxReferRge = acetateMaxReferRge;
		this.phosphateMaxReferRge = phosphateMaxReferRge;
		this.magnesiumMaxReferRge = magnesiumMaxReferRge;
		this.calciumMaxReferRge = calciumMaxReferRge;
		this.traceElementsSolnMinReferRge = traceElementsSolnMinReferRge;
		this.traceElementsSolnMaxReferRge = traceElementsSolnMaxReferRge;
		this.vitaminSolnMinReferRge = vitaminSolnMinReferRge;
		this.vitaminSolnMaxReferRge = vitaminSolnMaxReferRge;
		this.waterSolubleMinReferRge = waterSolubleMinReferRge;
		this.waterSolubleMaxReferRge = waterSolubleMaxReferRge;
		this.fatSolubleMinReferRge = fatSolubleMinReferRge;
		this.fatSolubleMaxReferRge = fatSolubleMaxReferRge;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.glutaminMin = glutaminMin;
		this.glutaminMax = glutaminMax;
		this.glutaminAvg = glutaminAvg;
	}

	@Id
	@Column(name = "refer_rge_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "refer_rge_seqno", sequenceName = "T_CONSTITUENTS_REF_RANGE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "refer_rge_seqno")
	public long getReferRgeSeqno() {
		return this.referRgeSeqno;
	}

	public void setReferRgeSeqno(long referRgeSeqno) {
		this.referRgeSeqno = referRgeSeqno;
	}

	@Column(name = "pn_generics")
	public Long getPnGenerics() {
		return this.pnGenerics;
	}

	public void setPnGenerics(Long pnGenerics) {
		this.pnGenerics = pnGenerics;
	}

	@Column(name = "age_group", length = 20)
	public String getAgeGroup() {
		return this.ageGroup;
	}

	public void setAgeGroup(String ageGroup) {
		this.ageGroup = ageGroup;
	}

	@Column(name = "age_from", precision = 8)
	public BigDecimal getAgeFrom() {
		return this.ageFrom;
	}

	public void setAgeFrom(BigDecimal ageFrom) {
		this.ageFrom = ageFrom;
	}

	@Column(name = "age_from_unit", length = 20)
	public String getAgeFromUnit() {
		return this.ageFromUnit;
	}

	public void setAgeFromUnit(String ageFromUnit) {
		this.ageFromUnit = ageFromUnit;
	}

	@Column(name = "age_to", precision = 8)
	public BigDecimal getAgeTo() {
		return this.ageTo;
	}

	public void setAgeTo(BigDecimal ageTo) {
		this.ageTo = ageTo;
	}

	@Column(name = "age_to_unit", length = 20)
	public String getAgeToUnit() {
		return this.ageToUnit;
	}

	public void setAgeToUnit(String ageToUnit) {
		this.ageToUnit = ageToUnit;
	}

	@Column(name = "protein_min_refer_rge", precision = 8)
	public BigDecimal getProteinMinReferRge() {
		return this.proteinMinReferRge;
	}

	public void setProteinMinReferRge(BigDecimal proteinMinReferRge) {
		this.proteinMinReferRge = proteinMinReferRge;
	}

	@Column(name = "carbohydrate_min_refer_rge", precision = 8)
	public BigDecimal getCarbohydrateMinReferRge() {
		return this.carbohydrateMinReferRge;
	}

	public void setCarbohydrateMinReferRge(BigDecimal carbohydrateMinReferRge) {
		this.carbohydrateMinReferRge = carbohydrateMinReferRge;
	}

	@Column(name = "lipid_min_refer_rge", precision = 8)
	public BigDecimal getLipidMinReferRge() {
		return this.lipidMinReferRge;
	}

	public void setLipidMinReferRge(BigDecimal lipidMinReferRge) {
		this.lipidMinReferRge = lipidMinReferRge;
	}

	@Column(name = "protein_max_refer_rge", precision = 8)
	public BigDecimal getProteinMaxReferRge() {
		return this.proteinMaxReferRge;
	}

	public void setProteinMaxReferRge(BigDecimal proteinMaxReferRge) {
		this.proteinMaxReferRge = proteinMaxReferRge;
	}

	@Column(name = "carbohydrate_max_refer_rge", precision = 8)
	public BigDecimal getCarbohydrateMaxReferRge() {
		return this.carbohydrateMaxReferRge;
	}

	public void setCarbohydrateMaxReferRge(BigDecimal carbohydrateMaxReferRge) {
		this.carbohydrateMaxReferRge = carbohydrateMaxReferRge;
	}

	@Column(name = "lipid_max_refer_rge", precision = 8)
	public BigDecimal getLipidMaxReferRge() {
		return this.lipidMaxReferRge;
	}

	public void setLipidMaxReferRge(BigDecimal lipidMaxReferRge) {
		this.lipidMaxReferRge = lipidMaxReferRge;
	}

	@Column(name = "carbohydrate_refer_rge_unit", precision = 8)
	public BigDecimal getCarbohydrateReferRgeUnit() {
		return this.carbohydrateReferRgeUnit;
	}

	public void setCarbohydrateReferRgeUnit(BigDecimal carbohydrateReferRgeUnit) {
		this.carbohydrateReferRgeUnit = carbohydrateReferRgeUnit;
	}

	@Column(name = "sodium_min_refer_rge", precision = 8)
	public BigDecimal getSodiumMinReferRge() {
		return this.sodiumMinReferRge;
	}

	public void setSodiumMinReferRge(BigDecimal sodiumMinReferRge) {
		this.sodiumMinReferRge = sodiumMinReferRge;
	}

	@Column(name = "potassium_min_refer_rge", precision = 8)
	public BigDecimal getPotassiumMinReferRge() {
		return this.potassiumMinReferRge;
	}

	public void setPotassiumMinReferRge(BigDecimal potassiumMinReferRge) {
		this.potassiumMinReferRge = potassiumMinReferRge;
	}

	@Column(name = "chloride_min_refer_rge", precision = 8)
	public BigDecimal getChlorideMinReferRge() {
		return this.chlorideMinReferRge;
	}

	public void setChlorideMinReferRge(BigDecimal chlorideMinReferRge) {
		this.chlorideMinReferRge = chlorideMinReferRge;
	}

	@Column(name = "acetate_min_refer_rge", precision = 8)
	public BigDecimal getAcetateMinReferRge() {
		return this.acetateMinReferRge;
	}

	public void setAcetateMinReferRge(BigDecimal acetateMinReferRge) {
		this.acetateMinReferRge = acetateMinReferRge;
	}

	@Column(name = "phosphate_min_refer_rge", precision = 8)
	public BigDecimal getPhosphateMinReferRge() {
		return this.phosphateMinReferRge;
	}

	public void setPhosphateMinReferRge(BigDecimal phosphateMinReferRge) {
		this.phosphateMinReferRge = phosphateMinReferRge;
	}

	@Column(name = "magnesium_min_refer_rge", precision = 8)
	public BigDecimal getMagnesiumMinReferRge() {
		return this.magnesiumMinReferRge;
	}

	public void setMagnesiumMinReferRge(BigDecimal magnesiumMinReferRge) {
		this.magnesiumMinReferRge = magnesiumMinReferRge;
	}

	@Column(name = "calcium_min_refer_rge", precision = 8)
	public BigDecimal getCalciumMinReferRge() {
		return this.calciumMinReferRge;
	}

	public void setCalciumMinReferRge(BigDecimal calciumMinReferRge) {
		this.calciumMinReferRge = calciumMinReferRge;
	}

	@Column(name = "sodium_max_refer_rge", precision = 8)
	public BigDecimal getSodiumMaxReferRge() {
		return this.sodiumMaxReferRge;
	}

	public void setSodiumMaxReferRge(BigDecimal sodiumMaxReferRge) {
		this.sodiumMaxReferRge = sodiumMaxReferRge;
	}

	@Column(name = "potassium_max_refer_rge", precision = 8)
	public BigDecimal getPotassiumMaxReferRge() {
		return this.potassiumMaxReferRge;
	}

	public void setPotassiumMaxReferRge(BigDecimal potassiumMaxReferRge) {
		this.potassiumMaxReferRge = potassiumMaxReferRge;
	}

	@Column(name = "chloride_max_refer_rge", precision = 8)
	public BigDecimal getChlorideMaxReferRge() {
		return this.chlorideMaxReferRge;
	}

	public void setChlorideMaxReferRge(BigDecimal chlorideMaxReferRge) {
		this.chlorideMaxReferRge = chlorideMaxReferRge;
	}

	@Column(name = "acetate_max_refer_rge", precision = 8)
	public BigDecimal getAcetateMaxReferRge() {
		return this.acetateMaxReferRge;
	}

	public void setAcetateMaxReferRge(BigDecimal acetateMaxReferRge) {
		this.acetateMaxReferRge = acetateMaxReferRge;
	}

	@Column(name = "phosphate_max_refer_rge", precision = 8)
	public BigDecimal getPhosphateMaxReferRge() {
		return this.phosphateMaxReferRge;
	}

	public void setPhosphateMaxReferRge(BigDecimal phosphateMaxReferRge) {
		this.phosphateMaxReferRge = phosphateMaxReferRge;
	}

	@Column(name = "magnesium_max_refer_rge", precision = 8)
	public BigDecimal getMagnesiumMaxReferRge() {
		return this.magnesiumMaxReferRge;
	}

	public void setMagnesiumMaxReferRge(BigDecimal magnesiumMaxReferRge) {
		this.magnesiumMaxReferRge = magnesiumMaxReferRge;
	}

	@Column(name = "calcium_max_refer_rge", precision = 8)
	public BigDecimal getCalciumMaxReferRge() {
		return this.calciumMaxReferRge;
	}

	public void setCalciumMaxReferRge(BigDecimal calciumMaxReferRge) {
		this.calciumMaxReferRge = calciumMaxReferRge;
	}

	@Column(name = "TRACE_ELMNT_SOLN_MIN_REF_RGE", precision = 8)
	public BigDecimal getTraceElementsSolnMinReferRge() {
		return this.traceElementsSolnMinReferRge;
	}

	public void setTraceElementsSolnMinReferRge(
			BigDecimal traceElementsSolnMinReferRge) {
		this.traceElementsSolnMinReferRge = traceElementsSolnMinReferRge;
	}

	@Column(name = "TRACE_ELMNT_SOLN_MAX_REF_RGE", precision = 8)
	public BigDecimal getTraceElementsSolnMaxReferRge() {
		return this.traceElementsSolnMaxReferRge;
	}

	public void setTraceElementsSolnMaxReferRge(
			BigDecimal traceElementsSolnMaxReferRge) {
		this.traceElementsSolnMaxReferRge = traceElementsSolnMaxReferRge;
	}

	@Column(name = "vitamin_soln_min_refer_rge", precision = 8)
	public BigDecimal getVitaminSolnMinReferRge() {
		return this.vitaminSolnMinReferRge;
	}

	public void setVitaminSolnMinReferRge(BigDecimal vitaminSolnMinReferRge) {
		this.vitaminSolnMinReferRge = vitaminSolnMinReferRge;
	}

	@Column(name = "vitamin_soln_max_refer_rge", precision = 8)
	public BigDecimal getVitaminSolnMaxReferRge() {
		return this.vitaminSolnMaxReferRge;
	}

	public void setVitaminSolnMaxReferRge(BigDecimal vitaminSolnMaxReferRge) {
		this.vitaminSolnMaxReferRge = vitaminSolnMaxReferRge;
	}

	@Column(name = "water_soluble_min_refer_rge", precision = 8)
	public BigDecimal getWaterSolubleMinReferRge() {
		return this.waterSolubleMinReferRge;
	}

	public void setWaterSolubleMinReferRge(BigDecimal waterSolubleMinReferRge) {
		this.waterSolubleMinReferRge = waterSolubleMinReferRge;
	}

	@Column(name = "water_soluble_max_refer_rge", precision = 8)
	public BigDecimal getWaterSolubleMaxReferRge() {
		return this.waterSolubleMaxReferRge;
	}

	public void setWaterSolubleMaxReferRge(BigDecimal waterSolubleMaxReferRge) {
		this.waterSolubleMaxReferRge = waterSolubleMaxReferRge;
	}

	@Column(name = "fat_soluble_min_refer_rge", precision = 8)
	public BigDecimal getFatSolubleMinReferRge() {
		return this.fatSolubleMinReferRge;
	}

	public void setFatSolubleMinReferRge(BigDecimal fatSolubleMinReferRge) {
		this.fatSolubleMinReferRge = fatSolubleMinReferRge;
	}

	@Column(name = "fat_soluble_max_refer_rge", precision = 8)
	public BigDecimal getFatSolubleMaxReferRge() {
		return this.fatSolubleMaxReferRge;
	}

	public void setFatSolubleMaxReferRge(BigDecimal fatSolubleMaxReferRge) {
		this.fatSolubleMaxReferRge = fatSolubleMaxReferRge;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public void setGlutaminMin(BigDecimal glutaminMin) {
		this.glutaminMin = glutaminMin;
	}
	
	@Column(name = "glutamin_min", precision = 8)
	public BigDecimal getGlutaminMin() {
		return glutaminMin;
	}

	public void setGlutaminMax(BigDecimal glutaminMax) {
		this.glutaminMax = glutaminMax;
	}
	
	@Column(name = "glutamin_max", precision = 8)
	public BigDecimal getGlutaminMax() {
		return glutaminMax;
	}

	public void setGlutaminAvg(BigDecimal glutaminAvg) {
		this.glutaminAvg = glutaminAvg;
	}

	@Column(name = "glutamin_avg", precision = 8)
	public BigDecimal getGlutaminAvg() {
		return glutaminAvg;
	}

}
