package my.com.cmg.iwp.maintenance.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DrugIndication generated by hbm2java
 */
@Entity
@Table(name = "t_drug_indications", uniqueConstraints = @UniqueConstraint(columnNames = {
		"drug_seqno", "indication_seqno" }))
public class DrugIndication implements java.io.Serializable {
	private static final long serialVersionUID = -4108046849037816561L;
	private long drugIndSeqno = Long.MIN_VALUE;
	private Drug drug;
	private Indication indication;
	private Character defaultYn = 'N';
	private String guidelineInfo;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private long indicationSeqno;

	public DrugIndication() {
	}

	public DrugIndication(long drugIndSeqno, Drug drug, Indication indication,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.drugIndSeqno = drugIndSeqno;
		this.drug = drug;
		this.indication = indication;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public DrugIndication(long drugIndSeqno, Drug drug, Indication indication,
			String parameter1, String parameter2, BigDecimal parameter3,
			BigDecimal parameter4, Date parameter5, Character activeFlag,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.drugIndSeqno = drugIndSeqno;
		this.drug = drug;
		this.indication = indication;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "drug_ind_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "drug_ind_seqno", sequenceName = "t_drug_indications_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "drug_ind_seqno")
	public long getDrugIndSeqno() {
		return this.drugIndSeqno;
	}

	public void setDrugIndSeqno(long drugIndSeqno) {
		this.drugIndSeqno = drugIndSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_seqno", nullable = false)
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "indication_seqno", nullable = false, insertable = true, updatable = true)
	public Indication getIndication() {
		return this.indication;
	}

	public void setIndication(Indication indication) {
		this.indication = indication;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "default_yn")
	public Character getDefaultYn() {
		return defaultYn;
	}

	public void setDefaultYn(Character defaultYn) {
		this.defaultYn = defaultYn;
	}

	@Column(name = "indication_seqno", nullable = false, insertable = false, updatable = false)
	public long getIndicationSeqno() {
		return indicationSeqno;
	}

	public void setIndicationSeqno(long indicationSeqno) {
		this.indicationSeqno = indicationSeqno;
	}
	
	@Column(name = "guideline_info")
	public String getGuidelineInfo() {
		return guidelineInfo;
	}

	public void setGuidelineInfo(String guidelineInfo) {
		this.guidelineInfo = guidelineInfo;
	}
}