package my.com.cmg.iwp.maintenance.model;

// Generated Apr 27, 2012 12:07:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrugExtemp generated by hbm2java
 */
@Entity
@Table(name = "t_drug_extemps")
public class DrugExtemp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5241633256416693508L;
	private long drugExtempSeqno = Long.MIN_VALUE;
	private Drug drug;
	private String prepName;
	private BigDecimal concentration;
	private String codeSuffix;
	private String vehicle;
//	private Character defaultYn = 'N';
	private int expiry;
	private String storageCondition;
	private String storageLocal;
	private String referencesFormula;
	private String remark;
	private String proceduresPhar;
	private String proceduresLocal;
	private String addItem1;
	private String addItem2;
	private String addItem3;
	private String addItem4;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private long drugSeqno;

	public DrugExtemp() {
	}

	@Id
	@Column(name = "drug_extemp_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "drugExtempSEQ", sequenceName = "t_drug_extemps_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "drugExtempSEQ")
	public long getDrugExtempSeqno() {
		return this.drugExtempSeqno;
	}

	public void setDrugExtempSeqno(long drugExtempSeqno) {
		this.drugExtempSeqno = drugExtempSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_seqno", insertable = true, updatable = true)
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@Column(name = "vehicle", length = 100)
	public String getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(String vehicle) {
		this.vehicle = vehicle;
	}

	@Column(name = "remark", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "prep_name", length = 40)
	public String getPrepName() {
		return prepName;
	}

	public void setPrepName(String prepName) {
		this.prepName = prepName;
	}

	@Column(name = "concentration")
	public BigDecimal getConcentration() {
		return concentration;
	}

	public void setConcentration(BigDecimal concentration) {
		this.concentration = concentration;
	}

	@Column(name = "code_suffix", length = 10)
	public String getCodeSuffix() {
		return codeSuffix;
	}

	public void setCodeSuffix(String codeSuffix) {
		this.codeSuffix = codeSuffix;
	}

	/*@Column(name = "default_yn")
	public Character getDefaultYn() {
		return defaultYn;
	}

	public void setDefaultYn(Character defaultYn) {
		this.defaultYn = defaultYn;
	}*/

	@Column(name = "expiry")
	public int getExpiry() {
		return expiry;
	}

	public void setExpiry(int expiry) {
		this.expiry = expiry;
	}

	@Column(name = "storage_condition", length = 250)
	public String getStorageCondition() {
		return storageCondition;
	}

	public void setStorageCondition(String storageCondition) {
		this.storageCondition = storageCondition;
	}

	@Column(name = "storage_local", length = 250)
	public String getStorageLocal() {
		return storageLocal;
	}

	public void setStorageLocal(String storageLocal) {
		this.storageLocal = storageLocal;
	}

	@Column(name = "references_formula", length = 500)
	public String getReferencesFormula() {
		return referencesFormula;
	}

	public void setReferencesFormula(String referencesFormula) {
		this.referencesFormula = referencesFormula;
	}

	@Column(name = "procedures_phar", length = 1000)
	public String getProceduresPhar() {
		return proceduresPhar;
	}

	public void setProceduresPhar(String proceduresPhar) {
		this.proceduresPhar = proceduresPhar;
	}

	@Column(name = "procedures_local", length = 1000)
	public String getProceduresLocal() {
		return proceduresLocal;
	}

	public void setProceduresLocal(String proceduresLocal) {
		this.proceduresLocal = proceduresLocal;
	}

	@Column(name = "add_item1", length = 100)
	public String getAddItem1() {
		return addItem1;
	}

	public void setAddItem1(String addItem1) {
		this.addItem1 = addItem1;
	}

	@Column(name = "add_item2", length = 100)
	public String getAddItem2() {
		return addItem2;
	}

	public void setAddItem2(String addItem2) {
		this.addItem2 = addItem2;
	}

	@Column(name = "add_item3", length = 100)
	public String getAddItem3() {
		return addItem3;
	}

	public void setAddItem3(String addItem3) {
		this.addItem3 = addItem3;
	}

	@Column(name = "add_item4", length = 100)
	public String getAddItem4() {
		return addItem4;
	}

	public void setAddItem4(String addItem4) {
		this.addItem4 = addItem4;
	}

	public void setDrugSeqno(long drugSeqno) {
		this.drugSeqno = drugSeqno;
	}

	@Column(name = "drug_seqno", insertable = false, updatable = false)
	public long getDrugSeqno() {
		return drugSeqno;
	}
}
