package my.com.cmg.iwp.maintenance.model;

// Generated 15 Mar, 2012 1:28:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrequencySchedule generated by hbm2java
 */
@Entity
@Table(name = "t_frequency_schedules")
public class FrequencySchedule implements java.io.Serializable, Comparable {
	private static final long serialVersionUID = -6715255191996947481L;
	private long scheduleSeqno = Long.MIN_VALUE;
	private Frequency frequency;
	private Date scheduleTime;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createBy;
	private Date createDate;
	private long updateBy;
	private Date updateDate;
	private RegimenDays regimenDays;

	public FrequencySchedule() {
	}

	public FrequencySchedule(long scheduleSeqno, Frequency frequency,
			Date scheduleTime, long createBy, Date createDate, long updateBy,
			Date updateDate) {
		this.scheduleSeqno = scheduleSeqno;
		this.frequency = frequency;
		this.scheduleTime = scheduleTime;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@Column(name = "schedule_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "scheduleSeqno", sequenceName = "t_frequency_schedules_seq", allocationSize = 1)
	@GeneratedValue(generator = "scheduleSeqno", strategy = GenerationType.SEQUENCE)
	public long getScheduleSeqno() {
		return scheduleSeqno;
	}

	public void setScheduleSeqno(long scheduleSeqno) {
		this.scheduleSeqno = scheduleSeqno;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "schedule_time", length = 15)
	public Date getScheduleTime() {
		return scheduleTime;
	}

	public void setScheduleTime(Date scheduleTime) {
		this.scheduleTime = scheduleTime;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(long createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(long updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setFrequency(Frequency frequency) {
		this.frequency = frequency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "freq_seqno", nullable = false)
	public Frequency getFrequency() {
		return frequency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regimen_day_seqno")
	public RegimenDays getRegimenDays() {
		return regimenDays;
	}

	public void setRegimenDays(RegimenDays regimenDays) {
		this.regimenDays = regimenDays;
	}

	@Override
	public int compareTo(Object o) {
		if(o instanceof FrequencySchedule)
			return this.getScheduleTime().compareTo(((FrequencySchedule) o).getScheduleTime());
		return 0;
	}
}