package my.com.cmg.iwp.maintenance.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * RequesterUnit generated by hbm2java
 */
@Entity
@Table(name = "t_requester_units", uniqueConstraints = @UniqueConstraint(columnNames = "rqstr_code"))
public class RequesterUnit implements java.io.Serializable,
		Comparable<RequesterUnit> {
	private static final long serialVersionUID = -5684312874101261484L;
	private long rqstrSeqno = Long.MIN_VALUE;

	private RequesterGroup requesterGroup;
	private String rqstrCode;

	private String unitGroup;
	private String unitType;

	private String rqstrDesc;
	private String totalBedNo;
	private short bufferLevel;
	private String bufferLevelType;
	private short minStorage;
	private String minStorageType;
	private short maxStorage;
	private String maxStorageType;
	private String rqstrStatus;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	private Long indentDrug;
	private Long indentNonDrug;
	private RequesterUnit requesterIndentDrug;
	private RequesterUnit requesterIndentNonDrug;
	private long groupSeqno;

	// Address Columns added here
	private String contactPerson;
	private String mobilePhone;
	private String officePhone;
	private String fax;
	private String email;
	private String fullAddress;

	public RequesterUnit() {
	}

	public RequesterUnit(long rqstrSeqno, String unitCode, Date createdDate,
			Date updatedDate) {
		this.rqstrSeqno = rqstrSeqno;
		this.rqstrCode = unitCode;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public RequesterUnit(long rqstrSeqno, RequesterGroup requesterGroup,
			String rqstrCode, String unitType, String rqstrDesc,
			String totalBedNo, short bufferLevel, String bufferLevelType,
			short minStorage, String minStorageType, short maxStorage,
			String maxStorageType, String rqstrStatus, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, Character activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate,
			Long indentDrug, Long indentNonDrug, String contactPerson,
			String address1, String address2, String address3, String city,
			String state, String postcode, String country,
			String organisationName, String homePhone, String mobilePhone,
			String officePhone, String fax, String email,
			RequesterUnit requesterIndentDrug,
			RequesterUnit requesterIndentNonDrug) {

		this.rqstrSeqno = rqstrSeqno;
		this.requesterGroup = requesterGroup;
		this.rqstrCode = rqstrCode;
		this.unitType = unitType;
		this.rqstrDesc = rqstrDesc;
		this.totalBedNo = totalBedNo;
		this.bufferLevel = bufferLevel;
		this.bufferLevelType = bufferLevelType;
		this.minStorage = minStorage;
		this.minStorageType = minStorageType;
		this.maxStorage = maxStorage;
		this.maxStorageType = maxStorageType;
		this.rqstrStatus = rqstrStatus;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.indentDrug = indentDrug;
		this.indentNonDrug = indentNonDrug;
		this.contactPerson = contactPerson;
		this.mobilePhone = mobilePhone;
		this.officePhone = officePhone;
		this.fax = fax;
		this.email = email;
		this.requesterIndentDrug = requesterIndentDrug;
		this.requesterIndentNonDrug = requesterIndentNonDrug;
	}

	@Id
	@Column(name = "rqstr_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "rqstr_seqno", sequenceName = "t_requester_units_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "rqstr_seqno")
	public long getRqstrSeqno() {
		return this.rqstrSeqno;
	}

	public void setRqstrSeqno(long rqstrSeqno) {
		this.rqstrSeqno = rqstrSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_seqno")
	public RequesterGroup getRequesterGroup() {
		return this.requesterGroup;
	}

	public void setRequesterGroup(RequesterGroup requesterGroup) {
		this.requesterGroup = requesterGroup;
	}

	@Column(name = "rqstr_code", nullable = false, length = 10)
	public String getRqstrCode() {
		return rqstrCode;
	}

	public void setRqstrCode(String rqstrCode) {
		this.rqstrCode = rqstrCode;
	}

	@Column(name = "unit_type", nullable = true, length = 10)
	public String getUnitType() {
		return this.unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	@Column(name = "rqstr_desc", nullable = false, length = 50)
	public String getRqstrDesc() {
		return this.rqstrDesc;
	}

	public void setRqstrDesc(String rqstrDesc) {
		this.rqstrDesc = rqstrDesc;
	}

	@Column(name = "total_bed_no", length = 3)
	public String getTotalBedNo() {
		return this.totalBedNo;
	}

	public void setTotalBedNo(String totalBedNo) {
		this.totalBedNo = totalBedNo;
	}

	@Column(name = "buffer_level", nullable = false)
	public short getBufferLevel() {
		return this.bufferLevel;
	}

	public void setBufferLevel(short bufferLevel) {
		this.bufferLevel = bufferLevel;
	}

	@Column(name = "buffer_level_type", nullable = false, length = 10)
	public String getBufferLevelType() {
		return this.bufferLevelType;
	}

	public void setBufferLevelType(String bufferLevelType) {
		this.bufferLevelType = bufferLevelType;
	}

	@Column(name = "min_storage", nullable = false)
	public short getMinStorage() {
		return this.minStorage;
	}

	public void setMinStorage(short minStorage) {
		this.minStorage = minStorage;
	}

	@Column(name = "min_storage_type", nullable = false, length = 10)
	public String getMinStorageType() {
		return this.minStorageType;
	}

	public void setMinStorageType(String minStorageType) {
		this.minStorageType = minStorageType;
	}

	@Column(name = "max_storage", nullable = false)
	public short getMaxStorage() {
		return this.maxStorage;
	}

	public void setMaxStorage(short maxStorage) {
		this.maxStorage = maxStorage;
	}

	@Column(name = "max_storage_type", nullable = false, length = 10)
	public String getMaxStorageType() {
		return this.maxStorageType;
	}

	public void setMaxStorageType(String maxStorageType) {
		this.maxStorageType = maxStorageType;
	}

	@Column(name = "rqstr_status", nullable = false, length = 10)
	public String getRqstrStatus() {
		return this.rqstrStatus;
	}

	public void setRqstrStatus(String rqstrStatus) {
		this.rqstrStatus = rqstrStatus;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "indentdrug", nullable = true, insertable = false, updatable = false)
	public Long getIndentDrug() {
		return this.indentDrug;
	}

	public void setIndentDrug(Long indentDrug) {
		this.indentDrug = indentDrug;
	}

	@Column(name = "indentnondrug", nullable = true, insertable = false, updatable = false)
	public Long getIndentNonDrug() {
		return this.indentNonDrug;
	}

	public void setIndentNonDrug(Long indentNonDrug) {
		this.indentNonDrug = indentNonDrug;
	}

	public void setUnitGroup(String unitGroup) {
		this.unitGroup = unitGroup;
	}

	@Column(name = "unit_group", length = 20)
	public String getUnitGroup() {
		return unitGroup;
	}

	@Column(name = "contact_person", length = 250)
	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "mobile_phone", length = 20)
	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "office_phone", length = 20)
	public String getOfficePhone() {
		return officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public int compareTo(RequesterUnit reqUnit) {
		// TODO Auto-generated method stub
		return this.rqstrDesc.compareTo(reqUnit.rqstrDesc);
	}

	@Transient
	public String getFullAddress() {
		String fullAddress = "";
		String add1 = "";
		String add2 = "";
		String add3 = "";
		String pdcity = "";
		String stat = "";

		fullAddress = add1 + add2 + add3 + pdcity + stat;

		return fullAddress;
	}

	public void setFullAddress(String fullAddress) {
		this.fullAddress = fullAddress;
	}

	@Column(name = "group_seqno", insertable = false, updatable = false)
	public long getGroupSeqno() {
		return groupSeqno;
	}

	public void setGroupSeqno(long groupSeqno) {
		this.groupSeqno = groupSeqno;
	}

	public void setRequesterIndentDrug(RequesterUnit requesterIndentDrug) {
		this.requesterIndentDrug = requesterIndentDrug;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "indentdrug")
	public RequesterUnit getRequesterIndentDrug() {
		return requesterIndentDrug;
	}

	public void setRequesterIndentNonDrug(RequesterUnit requesterIndentNonDrug) {
		this.requesterIndentNonDrug = requesterIndentNonDrug;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "indentnondrug")
	public RequesterUnit getRequesterIndentNonDrug() {
		return requesterIndentNonDrug;
	}
}