package my.com.cmg.iwp.maintenance.model;

// Generated Oct 23, 2012 10:10:27 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhTdmGuidelineHdrs generated by hbm2java
 */
@Entity
@Table(name = "t_tdm_guideline_hdrs")
public class TdmGuidelineHdrs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long hdrGuidlineSeqno = Long.MIN_VALUE;
	private Drug drug;
	private String remarks;
	private String timeReach;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private BigDecimal totalCostAnalysis;
	private Set<TdmGuidline> tdmGuidlines = new HashSet<TdmGuidline>(0);
	private Set<TdmDrugCalculator> tdmCalculator = new HashSet<TdmDrugCalculator>(0);

	public TdmGuidelineHdrs() {
	}

	public TdmGuidelineHdrs(long hdrGuidlineSeqno, long createdBy,
			long updatedBy) {
		this.hdrGuidlineSeqno = hdrGuidlineSeqno;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public TdmGuidelineHdrs(long hdrGuidlineSeqno, Long tdmDrug,
			String remarks, String timeReach,
			Character activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate,
			Set<TdmGuidline> tdmGuidlines) {
		this.hdrGuidlineSeqno = hdrGuidlineSeqno;
		this.remarks = remarks;
		this.timeReach = timeReach;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.tdmGuidlines = tdmGuidlines;
	}

	@Id
	@Column(name = "hdr_guidline_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "hdr_guidline_seqno", sequenceName = "t_tdm_guideline_hdrs_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "hdr_guidline_seqno")
	public long getHdrGuidlineSeqno() {
		return this.hdrGuidlineSeqno;
	}

	public void setHdrGuidlineSeqno(long hdrGuidlineSeqno) {
		this.hdrGuidlineSeqno = hdrGuidlineSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tdm_drug")
	public Drug getDrug() {
		return drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "time_reach")
	public String getTimeReach() {
		return this.timeReach;
	}

	public void setTimeReach(String timeReach) {
		this.timeReach = timeReach;
	}
	

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 13)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tdmGuidelineHdrs", cascade = CascadeType.ALL)
	public Set<TdmGuidline> getTdmGuidlines() {
		return this.tdmGuidlines;
	}

	public void setTdmGuidlines(Set<TdmGuidline> tdmGuidlines) {
		this.tdmGuidlines = tdmGuidlines;
	}

	/**
	 * @return the tdmCalculator
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tdmGuidelineHdrs", cascade = CascadeType.ALL)
	public Set<TdmDrugCalculator> getTdmCalculator() {
		return tdmCalculator;
	}

	/**
	 * @param tdmCalculator the tdmCalculator to set
	 */
	public void setTdmCalculator(Set<TdmDrugCalculator> tdmCalculator) {
		this.tdmCalculator = tdmCalculator;
	}
	
	@Column(name = "totalcost_analysis")
	public BigDecimal getTotalCostAnalysis() {
		return totalCostAnalysis;
	}

	public void setTotalCostAnalysis(BigDecimal totalCostAnalysis) {
		this.totalCostAnalysis = totalCostAnalysis;
	}
}
