package my.com.cmg.iwp.maintenance.model;

// Generated Oct 23, 2012 10:10:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhTdmGuidline generated by hbm2java
 */
@Entity
@Table(name = "t_tdm_guideline")
public class TdmGuidline implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long dtlGuidlineSeqno = Long.MIN_VALUE;
	private String uom;
	private TdmGuidelineHdrs tdmGuidelineHdrs;
	private String samplingType;
	private String afterBefore;
	private String defaultTime;
	private String labOrder;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private String defaultTimeType;

	private String therapeuticRange;
	
	TdmGuidline tdmGuidline;
	
	public TdmGuidline() {
	}

	public TdmGuidline(long dtlGuidlineSeqno,
			TdmGuidelineHdrs tdmGuidelineHdrs, long createdBy, long updatedBy) {
		this.dtlGuidlineSeqno = dtlGuidlineSeqno;
		this.tdmGuidelineHdrs = tdmGuidelineHdrs;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public TdmGuidline(long dtlGuidlineSeqno, String uom,
			TdmGuidelineHdrs tdmGuidelineHdrs, String samplingType,
			String afterBefore, String defaultTime,			
			String labOrder, 
			Character activeFlag, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate) {
		this.dtlGuidlineSeqno = dtlGuidlineSeqno;
		this.uom = uom;
		this.tdmGuidelineHdrs = tdmGuidelineHdrs;
		this.samplingType = samplingType;
		this.afterBefore = afterBefore;
		this.defaultTime = defaultTime;
		this.labOrder = labOrder;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public TdmGuidline(TdmGuidline anTdmGuidline) {
		tdmGuidline = anTdmGuidline;
	}

	@Id
	@Column(name = "dtl_guidline_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "dtl_guidline_seqno", sequenceName = "t_tdm_guideline_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "dtl_guidline_seqno")
	public long getDtlGuidlineSeqno() {
		return this.dtlGuidlineSeqno;
	}

	public void setDtlGuidlineSeqno(long dtlGuidlineSeqno) {
		this.dtlGuidlineSeqno = dtlGuidlineSeqno;
	}

	
	@Column(name = "uom_seqno", length = 20)
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hdr_guidline_seqno", nullable = false)
	public TdmGuidelineHdrs getTdmGuidelineHdrs() {
		return this.tdmGuidelineHdrs;
	}

	public void setTdmGuidelineHdrs(TdmGuidelineHdrs phTdmGuidelineHdrs) {
		this.tdmGuidelineHdrs = phTdmGuidelineHdrs;
	}

	@Column(name = "sampling_type", length = 100)
	public String getSamplingType() {
		return this.samplingType;
	}

	public void setSamplingType(String samplingType) {
		this.samplingType = samplingType;
	}

	@Column(name = "after_before", length = 100)
	public String getAfterBefore() {
		return this.afterBefore;
	}

	public void setAfterBefore(String afterBefore) {
		this.afterBefore = afterBefore;
	}

	@Column(name = "default_time", length = 5)
	public String getDefaultTime() {
		return this.defaultTime;
	}

	public void setDefaultTime(String defaultTime) {
		this.defaultTime = defaultTime;
	}

	@Column(name = "lab_order", length = 20)
	public String getLabOrder() {
		return this.labOrder;
	}

	public void setLabOrder(String labOrder) {
		this.labOrder = labOrder;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 13)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "therapeutic_range", length = 1000)
	public String getTherapeuticRange() {
		return therapeuticRange;
	}

	public void setTherapeuticRange(String therapeuticRange) {
		this.therapeuticRange = therapeuticRange;
	}
	
	
	@Column(name = "default_time_type", length = 100)
	public String getDefaultTimeType() {
		return defaultTimeType;
	}

	public void setDefaultTimeType(String defaultTimeType) {
		this.defaultTimeType = defaultTimeType;
	}
}
