package my.com.cmg.iwp.maintenance.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrugRoute generated by hbm2java
 */
@Entity
@Table(name = "t_drug_routes")
public class DrugRoute implements java.io.Serializable {
	private static final long serialVersionUID = -316184223448300176L;
	private long drugRouteSeqno = Long.MIN_VALUE;
	private Drug drug;
	private AdminRoute adminRoute;
	private Character defaultRouteYn;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createBy;
	private Date createDate;
	private long updateBy;
	private Date updateDate;

	public DrugRoute() {
	}

	public DrugRoute(long drugRouteSeqno, Drug drug) {
		this.drugRouteSeqno = drugRouteSeqno;
		this.drug = drug;

	}

	public DrugRoute(long drugRouteSeqno, Drug drug, Character defaultRouteYn) {
		this.drugRouteSeqno = drugRouteSeqno;
		this.drug = drug;
		this.defaultRouteYn = defaultRouteYn;

	}

	@Id
	@Column(name = "route_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "drugRouteSEQ", sequenceName = "t_drug_routes_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "drugRouteSEQ")
	public long getDrugRouteSeqno() {
		return this.drugRouteSeqno;
	}

	public void setDrugRouteSeqno(long drugRouteSeqno) {
		this.drugRouteSeqno = drugRouteSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_seqno", nullable = false)
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@Column(name = "default_route_hq")
	public Character getDefaultRouteYn() {
		return this.defaultRouteYn;
	}

	public void setDefaultRouteYn(Character defaultRouteYn) {
		this.defaultRouteYn = defaultRouteYn;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by")
	public long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(long createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "updated_by")
	public long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(long updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setAdminRoute(AdminRoute adminRoute) {
		this.adminRoute = adminRoute;
	}

	@ManyToOne
	@JoinColumn(name = "route_code_seqno", nullable = false)
	// @Column(name = "route_code_seqno", length = 20)
	public AdminRoute getAdminRoute() {
		return adminRoute;
	}
}