// default package
// Generated Jul 16, 2012 2:26:41 PM by Hibernate Tools 3.4.0.CR1
package my.com.cmg.iwp.maintenance.model;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import my.com.cmg.iwp.webui.constant.RefCodeConstant;


/**
 * PhFormulationHeader generated by hbm2java
 */
@Entity
@Table(name = "t_formulation_header")
public class FormulationHeader implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private long formulaSeqno;
	private Item item;
	private Drug drug;
	private BigDecimal versionNo;
	private String status;
	private String formType;
	private SecUser createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;
	private Date approvedDate;
	private SecUser approvedBy;
	private BigDecimal formulaQty;
	private Uom formulaUom;
	private Character quarantine;
	private String preparationType;
	private BigDecimal packSize;
	private Uom packSizeUom;
	private Integer shelfLife;
	private String shelfLifeUnit;
	private String remarks;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private String formulaReference;
	private String deleteReason;
	private Character protectLight = RefCodeConstant.BOOLEAN_FALSE;
	private Character roomTempt = RefCodeConstant.BOOLEAN_FALSE;
	private Character refrigerate = RefCodeConstant.BOOLEAN_FALSE;
	private Character below0C = RefCodeConstant.BOOLEAN_FALSE;
	private Set<FormulationMaterial> formulationMaterials = new HashSet<FormulationMaterial>(0);

//	private Set<WorkorderHeader> workorderHeaders = new HashSet<WorkorderHeader>(0);
	
	private Set<FormulationSop> formulationSops = new HashSet<FormulationSop>(0);

	
	public FormulationHeader() {
	}

	public FormulationHeader(long formulaSeqno, SecUser createdBy,
			Date createdDate, Long updatedBy, Date updatedDate) {
		this.formulaSeqno = formulaSeqno;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public FormulationHeader(long formulaSeqno, String formulaItemCode,
			BigDecimal versionNo, String status, String formType,
			Date dateModified, String modifiedBy, Date approvedDate,
			SecUser approvedBy, BigDecimal formulaQty, Uom formulaUom,
			Character quarantine, String preparationType, BigDecimal packSize,
			String remarks, String parameter1, String parameter2,
			BigDecimal parameter3, BigDecimal parameter4, Date parameter5,
			Character activeFlag, SecUser createdBy, Date createdDate,
			Long updatedBy, Date updatedDate,
			Set<FormulationMaterial> phFormulationMaterialses,
			Set<FormulationSop> phFormulationSops, Character protectLight, Character roomTempt, Character refrigerate, Character below0C) {
		this.formulaSeqno = formulaSeqno;
		this.versionNo = versionNo;
		this.status = status;
		this.formType = formType;
		this.approvedDate = approvedDate;
		this.approvedBy = approvedBy;
		this.formulaQty = formulaQty;
		this.formulaUom = formulaUom;
		this.quarantine = quarantine;
		this.preparationType = preparationType;
		this.packSize = packSize;
		this.remarks = remarks;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.formulationMaterials = phFormulationMaterialses;
//		this.workorderHeaders = phWorkorderHeaders;
		this.formulationSops = phFormulationSops;
		this.protectLight = protectLight;
		this.roomTempt = roomTempt;
		this.refrigerate = refrigerate;
		this.below0C = below0C;
	}

	@Id
	@Column(name = "formula_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "galenicalFormulationSeqGen", sequenceName = "t_formulation_header_seq", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "galenicalFormulationSeqGen")
	public long getFormulaSeqno() {
		return this.formulaSeqno;
	}

	public void setFormulaSeqno(long formulaSeqno) {
		this.formulaSeqno = formulaSeqno;
	}

	@Column(name = "version_no", precision = 4, scale = 2)
	public BigDecimal getVersion() {
		return this.versionNo;
	}

	public void setVersion(BigDecimal version) {
		this.versionNo = version;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "form_type", length = 1)
	public String getType() {
		return this.formType;
	}

	public void setType(String type) {
		this.formType = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approved_date", length = 13)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@ManyToOne
	@JoinColumn(name = "approved_by")
	public SecUser getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(SecUser approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Column(name = "formula_qty", precision = 9, scale = 5)
	public BigDecimal getFormulaQty() {
		return this.formulaQty;
	}

	public void setFormulaQty(BigDecimal formulaQty) {
		this.formulaQty = formulaQty;
	}

	@Column(name = "quarantine")
	public Character getQuarantine() {
		return this.quarantine;
	}

	public void setQuarantine(Character quarantine) {
		this.quarantine = quarantine;
	}

	@Column(name = "preparation_type", length = 3)
	public String getPreparationType() {
		return this.preparationType;
	}

	public void setPreparationType(String preparationType) {
		this.preparationType = preparationType;
	}

	@Column(name = "pack_size")
	public BigDecimal getPackSize() {
		return this.packSize;
	}

	public void setPackSize(BigDecimal packSize) {
		this.packSize = packSize;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@ManyToOne
	@JoinColumn(name = "created_by")
	public SecUser getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(SecUser createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name="formula_reference")
	public String getFormulaReference() {
		return formulaReference;
	}

	public void setFormulaReference(String formulaReference) {
		this.formulaReference = formulaReference;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulationHeader", cascade=CascadeType.REMOVE)
	public Set<FormulationMaterial> getFormulationMaterials() {
		return formulationMaterials;
	}

	public void setFormulationMaterials(
			Set<FormulationMaterial> formulationMaterials) {
		this.formulationMaterials = formulationMaterials;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulationHeader")
//	public Set<WorkorderHeader> getWorkorderHeaders() {
//		return workorderHeaders;
//	}
//
//	public void setWorkorderHeaders(Set<WorkorderHeader> workorderHeaders) {
//		this.workorderHeaders = workorderHeaders;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formulationHeader", cascade=CascadeType.REMOVE)
	public Set<FormulationSop> getFormulationSops() {
		return formulationSops;
	}

	public void setFormulationSops(Set<FormulationSop> formulationSops) {
		this.formulationSops = formulationSops;
	}
	
	@ManyToOne
	@JoinColumn(name="item_seqno")
	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}
	
	
	@ManyToOne
	@JoinColumn(name="drug_seqno")
	public Drug getDrug() {
		return drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@ManyToOne()
	@JoinColumn(name="uom")
	public Uom getFormulaUom() {
		return formulaUom;
	}

	public void setFormulaUom(Uom formulaUom) {
		this.formulaUom = formulaUom;
	}

	@ManyToOne()
	@JoinColumn(name="pack_size_uom")
	public Uom getPackSizeUom() {
		return packSizeUom;
	}
	
	public void setPackSizeUom(Uom packSizeUom) {
		this.packSizeUom = packSizeUom;
	}

	@Column(name="shelf_life")
	public Integer getShelfLife() {
		return shelfLife;
	}

	public void setShelfLife(Integer shelfLife) {
		this.shelfLife = shelfLife;
	}

	@Column(name="shelf_life_unit")
	public String getShelfLifeUnit() {
		return shelfLifeUnit;
	}

	public void setShelfLifeUnit(String shelfLifeUnit) {
		this.shelfLifeUnit = shelfLifeUnit;
	}
	
	@Column(name="delete_reason")
	public String getDeleteReason() {
		return deleteReason;
	}

	public void setDeleteReason(String deleteReason) {
		this.deleteReason = deleteReason;
	}

	@Column(name = "protectLightYN")
	public Character isProtectLight() {
		return this.protectLight;
	}

	public void setProtectLight(Character protectLight) {
		this.protectLight = protectLight;
	}

	@Column(name = "roomTemptYN")
	public Character isRoomTempt() {
		return this.roomTempt;
	}

	public void setRoomTempt(Character roomTempt) {
		this.roomTempt = roomTempt;
	}

	@Column(name = "refrigerateYN")
	public Character isRefrigerate() {
		return this.refrigerate;
	}

	public void setRefrigerate(Character refrigerate) {
		this.refrigerate = refrigerate;
	}

	@Column(name = "below0CYN")
	public Character isBelow0C() {
		return this.below0C;
	}

	public void setBelow0C(Character below0c) {
		this.below0C = below0c;
	}

}
