package my.com.cmg.iwp.maintenance.model;

// Generated 11 Dec, 2012 11:05:08 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhFaq generated by hbm2java
 */
@Entity
@Table(name = "t_faq")
public class Faq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long faqSeqno;
	private String publishFlag;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private String activeFlag;
	private Long createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;
	// private Long fcISeqno;
	private String question;
	private String response;
	private String publicFlag;
	private String communityFlag;
	private String publicpublishFlag;
	private Integer enquiryCount;
	private String communitypublishFlag;
	private long enquirySeqno;

	private String ptjCode;
	private String facCode;

	public Faq() {
	}

	public Faq(long faqSeqno, long createdBy, Date createdDate, long updatedBy,
			Date updatedDate) {
		this.faqSeqno = faqSeqno;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public Faq(long faqSeqno, String publishFlag, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, String activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate,
			String question, String response, String publicFlag,
			String communityFlag, int enquiryCount) {
		this.faqSeqno = faqSeqno;
		this.publishFlag = publishFlag;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		// this.fcISeqno = fcISeqno;
		this.question = question;
		this.response = response;
		this.publicFlag = publicFlag;
		this.communityFlag = communityFlag;
		this.enquiryCount = enquiryCount;
	}

	@Column(name = "public_publish_flag")
	public String getPublicpublishFlag() {
		return publicpublishFlag;
	}

	public void setPublicpublishFlag(String publicpublishFlag) {
		this.publicpublishFlag = publicpublishFlag;
	}

	@Column(name = "community_publish_flag")
	public String getCommunitypublishFlag() {
		return communitypublishFlag;
	}

	public void setCommunitypublishFlag(String communitypublishFlag) {
		this.communitypublishFlag = communitypublishFlag;
	}

	@Column(name = "public_flag")
	public String getPublicFlag() {
		return publicFlag;
	}

	public void setPublicFlag(String publicFlag) {
		this.publicFlag = publicFlag;
	}

	@Column(name = "community_flag")
	public String getCommunityFlag() {
		return communityFlag;
	}

	public void setCommunityFlag(String communityFlag) {
		this.communityFlag = communityFlag;
	}

	@Id
	@Column(name = "faq_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "phFaqSEQ", sequenceName = "t_faq_seq", allocationSize = 1)
	@GeneratedValue(generator = "phFaqSEQ")
	public long getFaqSeqno() {
		return this.faqSeqno;
	}

	public void setFaqSeqno(long faqSeqno) {
		this.faqSeqno = faqSeqno;
	}

	@Column(name = "publish_flag")
	public String getPublishFlag() {
		return this.publishFlag;
	}

	public void setPublishFlag(String publishFlag) {
		this.publishFlag = publishFlag;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public String getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	// @Column(name = "fc_i_seqno")
	// public Long getFcISeqno() {
	// return this.fcISeqno;
	// }
	//
	// public void setFcISeqno(Long fcISeqno) {
	// this.fcISeqno = fcISeqno;
	// }

	@Column(name = "question", length = 1000)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "response", length = 2000)
	public String getResponse() {
		return this.response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	@Column(name = "ptj_code")
	public String getPtjCode() {
		return ptjCode;
	}

	public void setPtjCode(String ptjCode) {
		this.ptjCode = ptjCode;
	}

	@Column(name = "fac_code")
	public String getFacCode() {
		return facCode;
	}

	public void setFacCode(String facCode) {
		this.facCode = facCode;
	}

	public void setEnquiryCount(Integer enquiryCount) {
		this.enquiryCount = enquiryCount;
	}
	
	@Column(name = "enquiry_count")
	public Integer getEnquiryCount() {
		return enquiryCount;
	}
	
	@Column(name = "PH_ENQUIRY_SEQNO")
	public long getEnquirySeqno() {
		return enquirySeqno;
	}

	public void setEnquirySeqno(long enquirySeqno) {
		this.enquirySeqno = enquirySeqno;
	}


}
