package my.com.cmg.iwp.backend.model.integration.rp;
// default package
// Generated May 13, 2013 6:37:50 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlElement;

import org.hibernate.annotations.IndexColumn;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import my.com.cmg.iwp.backend.model.integration.OutsourceOrderInt;
import my.com.cmg.iwp.webui.constant.RefCodeConstant;


/**
 * PhOrderRpInt generated by hbm2java
 */
@Entity
@Table(name = "t_order_rp_int")
@JsonIgnoreProperties(ignoreUnknown=true)
public class OrderRpInt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long orderRpSeqno;
	private String appNo;
	private BigDecimal amount;
	private Double dispenseQty;
	private String drugCode;
	private Date rpDate;
	private String counsellingYn;
	private String counsellingIndicator;
	private String orderRemarks;


	private String linkRpharmaCode;
	private String uomAbbreviation;

	private Integer timeHour;
	private String timeMinutes;

	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private String verificationStageRemark;
	private String preparationStageRemark;
	private String dispenseStageRemark;
	private OutsourceOrderInt outsourceOrderInt;
	private Double activityQty;
	private Character serviceType = RefCodeConstant.OUTSOURCE_REQUEST;
	private Date calActivityDateTime;
	private Set<DispenseRpBatchInt> dispenseRpBatchInts = new HashSet<DispenseRpBatchInt>(0);
	
	public OrderRpInt() {
	}

	public OrderRpInt(long orderRpSeqno) {
		super();
		this.orderRpSeqno = orderRpSeqno;
	}

	public OrderRpInt(long orderRpSeqno, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate) {
		this.orderRpSeqno = orderRpSeqno;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public OrderRpInt(long orderRpSeqno, String appNo, BigDecimal amount,
			String uomCode, String drugCode, Date rpDate,
			String counsellingYn, String counsellingIndicator,
			String orderRemarks, String discontinueRemarks, Date orderedDate,
			String linkRpharmaCode, String cancelReason, Integer timeHour,
			String timeMinutes, String orderStatus, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, Boolean activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.orderRpSeqno = orderRpSeqno;
		this.appNo = appNo;
		this.amount = amount;

		this.drugCode = drugCode;
		this.rpDate = rpDate;
		this.counsellingYn = counsellingYn;
		this.counsellingIndicator = counsellingIndicator;
		this.orderRemarks = orderRemarks;

		this.linkRpharmaCode = linkRpharmaCode;

		this.timeHour = timeHour;
		this.timeMinutes = timeMinutes;

		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@SequenceGenerator(name="ph_order_rp_int_seqno", sequenceName="t_order_rp_int_seq", allocationSize=1 )
	@GeneratedValue(generator="ph_order_rp_int_seqno")
	@Column(name = "order_rp_seqno", unique = true, nullable = false)
	@JsonIgnore
	public long getOrderRpSeqno() {
		return this.orderRpSeqno;
	}

	public void setOrderRpSeqno(long orderRpSeqno) {
		this.orderRpSeqno = orderRpSeqno;
	}

	@Column(name = "app_no", length = 12)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "amount", precision = 131089, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}



	@Column(name = "drug_code", length = 10)
	public String getDrugCode() {
		return this.drugCode;
	}

	public void setDrugCode(String drugCode) {
		this.drugCode = drugCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rp_date", length = 13)
	public Date getRpDate() {
		return this.rpDate;
	}

	public void setRpDate(Date rpDate) {
		this.rpDate = rpDate;
	}

	@Column(name = "counselling_yn")
	public String getCounsellingYn() {
		return this.counsellingYn;
	}

	public void setCounsellingYn(String counsellingYn) {
		this.counsellingYn = counsellingYn;
	}

	@Column(name = "counselling_indicator", length = 250)
	public String getCounsellingIndicator() {
		return this.counsellingIndicator;
	}

	public void setCounsellingIndicator(String counsellingIndicator) {
		this.counsellingIndicator = counsellingIndicator;
	}

	@Column(name = "order_remarks", length = 100)
	public String getOrderRemarks() {
		return this.orderRemarks;
	}

	public void setOrderRemarks(String orderRemarks) {
		this.orderRemarks = orderRemarks;
	}





	@Column(name = "link_rpharma_code", length = 10)
	public String getLinkRpharmaCode() {
		return this.linkRpharmaCode;
	}

	public void setLinkRpharmaCode(String linkRpharmaCode) {
		this.linkRpharmaCode = linkRpharmaCode;
	}

	@Column(name = "uom_abbreviation", length = 10)
	public String getUomAbbreviation() {
		return uomAbbreviation;
	}

	public void setUomAbbreviation(String uomAbbreviation) {
		this.uomAbbreviation = uomAbbreviation;
	}

	@Column(name = "time_hour")
	public Integer getTimeHour() {
		return this.timeHour;
	}

	public void setTimeHour(Integer timeHour) {
		this.timeHour = timeHour;
	}

	@Column(name = "time_minutes", length = 20)
	public String getTimeMinutes() {
		return this.timeMinutes;
	}

	public void setTimeMinutes(String timeMinutes) {
		this.timeMinutes = timeMinutes;
	}



	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@ManyToOne
	@JoinColumn(name="outsource_int_seqno", nullable = false)
	@JsonBackReference("RpOutsourceOrderInt")
	public OutsourceOrderInt getOutsourceOrderInt() {
		return this.outsourceOrderInt;
	}

	public void setOutsourceOrderInt(OutsourceOrderInt outsourceOrderInt) {
		this.outsourceOrderInt = outsourceOrderInt;
	}

	@Column(name = "disp_qty")
	public Double getDispenseQty() {
		return this.dispenseQty;
	}

	public void setDispenseQty(Double dispenseQty) {
		this.dispenseQty = dispenseQty;
	}

	@Column(name = "veri_remark", length = 250)
	public String getVerificationStageRemark() {
		return this.verificationStageRemark;
	}

	public void setVerificationStageRemark(String verificationStageRemark) {
		this.verificationStageRemark = verificationStageRemark;
	}

	@Column(name = "prep_remark", length = 250)
	public String getPreparationStageRemark() {
		return this.preparationStageRemark;
	}

	public void setPreparationStageRemark(String preparationStageRemark) {
		this.preparationStageRemark = preparationStageRemark;
	}

	@Column(name = "disp_remark", length = 250)
	public String getDispenseStageRemark() {
		return this.dispenseStageRemark;
	}

	public void setDispenseStageRemark(String dispenseStageRemark) {
		this.dispenseStageRemark = dispenseStageRemark;
	}
	
	@Column(name = "activity_qty")
	public Double getActivityQty() {
		return this.activityQty;
	}

	public void setActivityQty(Double activityQty) {
		this.activityQty = activityQty;
	}

	@Column(name = "service_type")
	public Character getServiceType() {
		return serviceType;
	}

	public void setServiceType(Character serviceType) {
		this.serviceType = serviceType;
	}
	
	@Column(name = "cal_activity_date_time")
	public Date getCalActivityDateTime() {
		return calActivityDateTime;
	}

	public void setCalActivityDateTime(Date calActivityDateTime) {
		this.calActivityDateTime = calActivityDateTime;
	}
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderRpInt", cascade= CascadeType.ALL)
	
	@OneToMany(mappedBy="orderRpInt", cascade = CascadeType.ALL)
	@IndexColumn(name="rp_batch_int_seqno")
	@XmlElement
	@JsonManagedReference("RpOutsourceOrderInt")
	public Set<DispenseRpBatchInt> getDispenseRpBatchInts() {
		return dispenseRpBatchInts;
	}

	public void setDispenseRpBatchInts(Set<DispenseRpBatchInt> dispenseRpBatchInts) {
		this.dispenseRpBatchInts = dispenseRpBatchInts;
	}
}
