package my.com.cmg.iwp.maintenance.model;

// Generated Nov 26, 2012 3:50:42 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhTpnSourceContent generated by hbm2java
 */
@Entity
@Table(name = "t_tpn_source_content")
public class TpnSourceContent implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long tpnSourceContentSeqno = Long.MIN_VALUE;
	private Drug drug;
	private Character tpnFlag;
	private Long cmmricalProduct;
	private BigDecimal volume;
	private BigDecimal aminoAcid;
	private BigDecimal glucose;
	private String glucoseUnit;
	private BigDecimal lipid;
	private BigDecimal totalEnergy;
	private BigDecimal sodium;
	private BigDecimal potassium;
	private BigDecimal caclium;
	private BigDecimal magnesium;
	private BigDecimal phosphate;
	private BigDecimal chloride;
	private BigDecimal acetate;
	private BigDecimal zinc;
	private BigDecimal osmolarity;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private BigDecimal traceElement;
	private BigDecimal vitaminSolution;
	private BigDecimal waterSoluble;
	private BigDecimal fatSoluble;
	private BigDecimal sodiumMax;
	private BigDecimal potassiumMax;
	private BigDecimal cacliumMax;
	private BigDecimal magnesiumMax;
	private BigDecimal phosphateMax;
	private BigDecimal chlorideMax;
	private BigDecimal acetateMax;
	private BigDecimal zincMax;
	private BigDecimal traceElementMax;
	private BigDecimal vitaminSolutionMax;
	private BigDecimal waterSolubleMax;
	private BigDecimal fatSolubleMax;

	public TpnSourceContent() {
	}

	public TpnSourceContent(long tpnSourceContentSeqno, Drug drug,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.tpnSourceContentSeqno = tpnSourceContentSeqno;
		this.drug = drug;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public TpnSourceContent(long tpnSourceContentSeqno, Drug drug,
			Character tpnFlag, Long cmmricalProduct, BigDecimal volume,
			BigDecimal aminoAcid, BigDecimal glucose, String glucoseUnit,
			BigDecimal lipid, BigDecimal totalEnergy, BigDecimal sodium,
			BigDecimal potassium, BigDecimal caclium, BigDecimal magnesium,
			BigDecimal phosphate, BigDecimal chloride, BigDecimal acetate,
			BigDecimal zinc, BigDecimal osmolarity, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, Character activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate, BigDecimal glutamin) {
		this.tpnSourceContentSeqno = tpnSourceContentSeqno;
		this.drug = drug;
		this.tpnFlag = tpnFlag;
		this.cmmricalProduct = cmmricalProduct;
		this.volume = volume;
		this.aminoAcid = aminoAcid;
		this.glucose = glucose;
		this.glucoseUnit = glucoseUnit;
		this.lipid = lipid;
		this.totalEnergy = totalEnergy;
		this.sodium = sodium;
		this.potassium = potassium;
		this.caclium = caclium;
		this.magnesium = magnesium;
		this.phosphate = phosphate;
		this.chloride = chloride;
		this.acetate = acetate;
		this.zinc = zinc;
		this.osmolarity = osmolarity;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "tpn_source_content_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "tpn_source_content_seqno", sequenceName = "t_tpn_source_content_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tpn_source_content_seqno")
	public long getTpnSourceContentSeqno() {
		return this.tpnSourceContentSeqno;
	}

	public void setTpnSourceContentSeqno(long tpnSourceContentSeqno) {
		this.tpnSourceContentSeqno = tpnSourceContentSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_seqno", nullable = false)
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@Column(name = "tpn_flag")
	public Character getTpnFlag() {
		return this.tpnFlag;
	}

	public void setTpnFlag(Character tpnFlag) {
		this.tpnFlag = tpnFlag;
	}

	@Column(name = "cmmrical_product")
	public Long getCmmricalProduct() {
		return this.cmmricalProduct;
	}

	public void setCmmricalProduct(Long cmmricalProduct) {
		this.cmmricalProduct = cmmricalProduct;
	}

	@Column(name = "volume", precision = 8)
	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	@Column(name = "amino_acid", precision = 8)
	public BigDecimal getAminoAcid() {
		return this.aminoAcid;
	}

	public void setAminoAcid(BigDecimal aminoAcid) {
		this.aminoAcid = aminoAcid;
	}

	@Column(name = "glucose", precision = 8)
	public BigDecimal getGlucose() {
		return this.glucose;
	}

	public void setGlucose(BigDecimal glucose) {
		this.glucose = glucose;
	}

	@Column(name = "glucose_unit", length = 20)
	public String getGlucoseUnit() {
		return this.glucoseUnit;
	}

	public void setGlucoseUnit(String glucoseUnit) {
		this.glucoseUnit = glucoseUnit;
	}

	@Column(name = "lipid", precision = 8)
	public BigDecimal getLipid() {
		return this.lipid;
	}

	public void setLipid(BigDecimal lipid) {
		this.lipid = lipid;
	}

	@Column(name = "total_energy", precision = 8)
	public BigDecimal getTotalEnergy() {
		return this.totalEnergy;
	}

	public void setTotalEnergy(BigDecimal totalEnergy) {
		this.totalEnergy = totalEnergy;
	}

	@Column(name = "sodium", precision = 8)
	public BigDecimal getSodium() {
		return this.sodium;
	}

	public void setSodium(BigDecimal sodium) {
		this.sodium = sodium;
	}

	@Column(name = "potassium", precision = 8)
	public BigDecimal getPotassium() {
		return this.potassium;
	}

	public void setPotassium(BigDecimal potassium) {
		this.potassium = potassium;
	}

	@Column(name = "caclium", precision = 8)
	public BigDecimal getCaclium() {
		return this.caclium;
	}

	public void setCaclium(BigDecimal caclium) {
		this.caclium = caclium;
	}

	@Column(name = "magnesium", precision = 8)
	public BigDecimal getMagnesium() {
		return this.magnesium;
	}

	public void setMagnesium(BigDecimal magnesium) {
		this.magnesium = magnesium;
	}

	@Column(name = "phosphate", precision = 8)
	public BigDecimal getPhosphate() {
		return this.phosphate;
	}

	public void setPhosphate(BigDecimal phosphate) {
		this.phosphate = phosphate;
	}

	@Column(name = "chloride", precision = 8)
	public BigDecimal getChloride() {
		return this.chloride;
	}

	public void setChloride(BigDecimal chloride) {
		this.chloride = chloride;
	}

	@Column(name = "acetate", precision = 8)
	public BigDecimal getAcetate() {
		return this.acetate;
	}

	public void setAcetate(BigDecimal acetate) {
		this.acetate = acetate;
	}

	@Column(name = "zinc", precision = 8)
	public BigDecimal getZinc() {
		return this.zinc;
	}

	public void setZinc(BigDecimal zinc) {
		this.zinc = zinc;
	}

	@Column(name = "osmolarity", precision = 8)
	public BigDecimal getOsmolarity() {
		return this.osmolarity;
	}

	public void setOsmolarity(BigDecimal osmolarity) {
		this.osmolarity = osmolarity;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	@Column(name = "trace_element", precision = 8)
	public BigDecimal getTraceElement() {
		return this.traceElement;
	}

	public void setTraceElement(BigDecimal traceElement) {
		this.traceElement = traceElement;
	}

	@Column(name = "vitamin_solution", precision = 8)
	public BigDecimal getVitaminSolution() {
		return this.vitaminSolution;
	}

	public void setVitaminSolution(BigDecimal vitaminSolution) {
		this.vitaminSolution = vitaminSolution;
	}

	@Column(name = "water_soluble", precision = 8)
	public BigDecimal getWaterSoluble() {
		return this.waterSoluble;
	}

	public void setWaterSoluble(BigDecimal waterSoluble) {
		this.waterSoluble = waterSoluble;
	}

	@Column(name = "fat_soluble", precision = 8)
	public BigDecimal getFatSoluble() {
		return this.fatSoluble;
	}

	public void setFatSoluble(BigDecimal fatSoluble) {
		this.fatSoluble = fatSoluble;
	}

	@Column(name = "sodium_max", precision = 8)
	public BigDecimal getSodiumMax() {
		return sodiumMax;
	}

	public void setSodiumMax(BigDecimal sodiumMax) {
		this.sodiumMax = sodiumMax;
	}

	@Column(name = "potassium_max", precision = 8)
	public BigDecimal getPotassiumMax() {
		return potassiumMax;
	}

	public void setPotassiumMax(BigDecimal potassiumMax) {
		this.potassiumMax = potassiumMax;
	}

	@Column(name = "caclium_max", precision = 8)
	public BigDecimal getCacliumMax() {
		return cacliumMax;
	}

	public void setCacliumMax(BigDecimal cacliumMax) {
		this.cacliumMax = cacliumMax;
	}

	@Column(name = "magnesium_max", precision = 8)
	public BigDecimal getMagnesiumMax() {
		return magnesiumMax;
	}

	public void setMagnesiumMax(BigDecimal magnesiumMax) {
		this.magnesiumMax = magnesiumMax;
	}

	@Column(name = "phosphate_max", precision = 8)
	public BigDecimal getPhosphateMax() {
		return phosphateMax;
	}

	public void setPhosphateMax(BigDecimal phosphateMax) {
		this.phosphateMax = phosphateMax;
	}

	@Column(name = "chloride_max", precision = 8)
	public BigDecimal getChlorideMax() {
		return chlorideMax;
	}

	public void setChlorideMax(BigDecimal chlorideMax) {
		this.chlorideMax = chlorideMax;
	}

	@Column(name = "acetate_max", precision = 8)
	public BigDecimal getAcetateMax() {
		return acetateMax;
	}

	public void setAcetateMax(BigDecimal acetateMax) {
		this.acetateMax = acetateMax;
	}

	@Column(name = "zinc_max", precision = 8)
	public BigDecimal getZincMax() {
		return zincMax;
	}

	public void setZincMax(BigDecimal zincMax) {
		this.zincMax = zincMax;
	}

	@Column(name = "trace_element_max", precision = 8)
	public BigDecimal getTraceElementMax() {
		return traceElementMax;
	}

	public void setTraceElementMax(BigDecimal traceElementMax) {
		this.traceElementMax = traceElementMax;
	}

	@Column(name = "vitamin_solution_max", precision = 8)
	public BigDecimal getVitaminSolutionMax() {
		return vitaminSolutionMax;
	}

	public void setVitaminSolutionMax(BigDecimal vitaminSolutionMax) {
		this.vitaminSolutionMax = vitaminSolutionMax;
	}

	@Column(name = "water_soluble_max", precision = 8)
	public BigDecimal getWaterSolubleMax() {
		return waterSolubleMax;
	}

	public void setWaterSolubleMax(BigDecimal waterSolubleMax) {
		this.waterSolubleMax = waterSolubleMax;
	}
	@Column(name = "fat_soluble_max", precision = 8)

	public BigDecimal getFatSolubleMax() {
		return fatSolubleMax;
	}

	public void setFatSolubleMax(BigDecimal fatSolubleMax) {
		this.fatSolubleMax = fatSolubleMax;
	}
}