package my.com.cmg.iwp.maintenance.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "t_dept_disciplines", uniqueConstraints = @UniqueConstraint(columnNames = {
		"dept_seqno", "discipline_seqno" }))
public class DepartmentDiscipline implements java.io.Serializable {
	private static final long serialVersionUID = 3064375923112253670L;
	private long deptDispSeqno = Long.MIN_VALUE;
	private Discipline discipline;
	private Department department;
	private long disciplineSeqno;
	private long deptSeqNo;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	public DepartmentDiscipline() {
	}

	public DepartmentDiscipline(long deptDispSeqno, long createBy,
			Date createDate, long updateBy, Date updateDate) {
		this.deptDispSeqno = deptDispSeqno;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
	}

	public DepartmentDiscipline(long deptDispSeqno, Discipline discipline,
			Department department, long createBy, Date createDate,
			long updateBy, Date updateDate) {
		this.deptDispSeqno = deptDispSeqno;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
		this.discipline = discipline;
		this.department = department;
	}

	@Id
	@Column(name = "dept_disp_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "deptDispSEQ", sequenceName = "t_dept_disciplines_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "deptDispSEQ")
	public long getDeptDispSeqno() {
		return this.deptDispSeqno;
	}

	public void setDeptDispSeqno(long deptDispSeqno) {
		this.deptDispSeqno = deptDispSeqno;
	}
	
	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by")
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createBy) {
		this.createdBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createDate) {
		this.createdDate = createDate;
	}

	@Column(name = "updated_by")
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updateBy) {
		this.updatedBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updateDate) {
		this.updatedDate = updateDate;
	}

	public void setDisciplineSeqno(long disciplineSeqno) {
		this.disciplineSeqno = disciplineSeqno;
	}

	@Column(name = "discipline_seqno", insertable = false, updatable = false)
	public long getDisciplineSeqno() {
		return disciplineSeqno;
	}

	public void setDeptSeqNo(long deptSeqNo) {
		this.deptSeqNo = deptSeqNo;
	}

	@Column(name = "dept_seqno", insertable = false, updatable = false)
	public long getDeptSeqNo() {
		return deptSeqNo;
	}

	public void setDiscipline(Discipline discipline) {
		this.discipline = discipline;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discipline_seqno")
	public Discipline getDiscipline() {
		return discipline;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dept_seqno")
	public Department getDepartment() {
		return department;
	}

}
