package my.com.cmg.iwp.backend.model.integration;
// default package
// Generated May 23, 2013 12:39:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * PhCurrentstkDtlsInt generated by hbm2java
 */
@Entity
@Table(name = "t_currentstk_dtls_int")
@JsonIgnoreProperties(ignoreUnknown=true)
public class CurrentstkDtlsInt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long stkdtlsIntSeqno;
	private CurrentstkHdrsInt currentstkHdrsInt;
	private String batchNo;
	private BigDecimal stkUnitPrice;
	private Date stkExpiryDate;
	private Date stkReceiveDate;
	private String stkSku;
	private long stkAvailableQty;
	private long stkAllocatedQty;
	private long stkTempCondemnQty;
	private char stkQuarantinedFlag;
	private long stkDispensedQty;
	private long stkBadStockQty;
	private Date batchExpiryDate;
	private String packDesc;
	private Long stkQuarantineQty;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	public CurrentstkDtlsInt() {
	}

	public CurrentstkDtlsInt(long stkdtlsIntSeqno,
			CurrentstkHdrsInt phCurrentstkHdrsInt, String batchNo,
			long stkAvailableQty, long stkAllocatedQty, long stkTempCondemnQty,
			char stkQuarantinedFlag, long stkDispensedQty, long stkBadStockQty,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.stkdtlsIntSeqno = stkdtlsIntSeqno;
		this.currentstkHdrsInt = phCurrentstkHdrsInt;
		this.batchNo = batchNo;
		this.stkAvailableQty = stkAvailableQty;
		this.stkAllocatedQty = stkAllocatedQty;
		this.stkTempCondemnQty = stkTempCondemnQty;
		this.stkQuarantinedFlag = stkQuarantinedFlag;
		this.stkDispensedQty = stkDispensedQty;
		this.stkBadStockQty = stkBadStockQty;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public CurrentstkDtlsInt(long stkdtlsIntSeqno,
			CurrentstkHdrsInt phCurrentstkHdrsInt, String batchNo,
			BigDecimal stkUnitPrice, Date stkExpiryDate, Date stkReceiveDate,
			String stkSku, long stkAvailableQty, long stkAllocatedQty,
			long stkTempCondemnQty, char stkQuarantinedFlag,
			long stkDispensedQty, long stkBadStockQty, Date batchExpiryDate,
			String packDesc, Long stkQuarantineQty, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, long createdBy, Date createdDate, long updatedBy,
			Date updatedDate) {
		this.stkdtlsIntSeqno = stkdtlsIntSeqno;
		this.currentstkHdrsInt = phCurrentstkHdrsInt;
		this.batchNo = batchNo;
		this.stkUnitPrice = stkUnitPrice;
		this.stkExpiryDate = stkExpiryDate;
		this.stkReceiveDate = stkReceiveDate;
		this.stkSku = stkSku;
		this.stkAvailableQty = stkAvailableQty;
		this.stkAllocatedQty = stkAllocatedQty;
		this.stkTempCondemnQty = stkTempCondemnQty;
		this.stkQuarantinedFlag = stkQuarantinedFlag;
		this.stkDispensedQty = stkDispensedQty;
		this.stkBadStockQty = stkBadStockQty;
		this.batchExpiryDate = batchExpiryDate;
		this.packDesc = packDesc;
		this.stkQuarantineQty = stkQuarantineQty;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@SequenceGenerator(name="ph_current_stk_dtl_int_seq", sequenceName="t_currentstk_dtls_int_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ph_current_stk_dtl_int_seq")
	@Column(name = "stkdtls_int_seqno", unique = true, nullable = false)
	@JsonIgnore
	public long getStkdtlsIntSeqno() {
		return this.stkdtlsIntSeqno;
	}

	public void setStkdtlsIntSeqno(long stkdtlsIntSeqno) {
		this.stkdtlsIntSeqno = stkdtlsIntSeqno;
	}

	@ManyToOne
	@JoinColumn(name = "stk_lot_int_no", nullable = false)
	@JsonBackReference("CurrentstkDtlsInt")
	public CurrentstkHdrsInt getCurrentstkHdrsInt() {
		return this.currentstkHdrsInt;
	}

	public void setCurrentstkHdrsInt(CurrentstkHdrsInt currentstkHdrsInt) {
		this.currentstkHdrsInt = currentstkHdrsInt;
	}

	@Column(name = "batch_no", nullable = false, length = 30)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "stk_unit_price", precision = 15, scale = 4)
	public BigDecimal getStkUnitPrice() {
		return this.stkUnitPrice;
	}

	public void setStkUnitPrice(BigDecimal stkUnitPrice) {
		this.stkUnitPrice = stkUnitPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "stk_expiry_date", length = 13)
	public Date getStkExpiryDate() {
		return this.stkExpiryDate;
	}

	public void setStkExpiryDate(Date stkExpiryDate) {
		this.stkExpiryDate = stkExpiryDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "stk_receive_date", length = 13)
	public Date getStkReceiveDate() {
		return this.stkReceiveDate;
	}

	public void setStkReceiveDate(Date stkReceiveDate) {
		this.stkReceiveDate = stkReceiveDate;
	}

	@Column(name = "stk_sku", length = 20)
	public String getStkSku() {
		return this.stkSku;
	}

	public void setStkSku(String stkSku) {
		this.stkSku = stkSku;
	}

	@Column(name = "stk_available_qty", nullable = false)
	public long getStkAvailableQty() {
		return this.stkAvailableQty;
	}

	public void setStkAvailableQty(long stkAvailableQty) {
		this.stkAvailableQty = stkAvailableQty;
	}

	@Column(name = "stk_allocated_qty", nullable = false)
	public long getStkAllocatedQty() {
		return this.stkAllocatedQty;
	}

	public void setStkAllocatedQty(long stkAllocatedQty) {
		this.stkAllocatedQty = stkAllocatedQty;
	}

	@Column(name = "stk_temp_condemn_qty", nullable = false)
	public long getStkTempCondemnQty() {
		return this.stkTempCondemnQty;
	}

	public void setStkTempCondemnQty(long stkTempCondemnQty) {
		this.stkTempCondemnQty = stkTempCondemnQty;
	}

	@Column(name = "stk_quarantined_flag", nullable = false, length = 1)
	public char getStkQuarantinedFlag() {
		return this.stkQuarantinedFlag;
	}

	public void setStkQuarantinedFlag(char stkQuarantinedFlag) {
		this.stkQuarantinedFlag = stkQuarantinedFlag;
	}

	@Column(name = "stk_dispensed_qty", nullable = false)
	public long getStkDispensedQty() {
		return this.stkDispensedQty;
	}

	public void setStkDispensedQty(long stkDispensedQty) {
		this.stkDispensedQty = stkDispensedQty;
	}

	@Column(name = "stk_bad_stock_qty", nullable = false)
	public long getStkBadStockQty() {
		return this.stkBadStockQty;
	}

	public void setStkBadStockQty(long stkBadStockQty) {
		this.stkBadStockQty = stkBadStockQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "batch_expiry_date", length = 29)
	public Date getBatchExpiryDate() {
		return this.batchExpiryDate;
	}

	public void setBatchExpiryDate(Date batchExpiryDate) {
		this.batchExpiryDate = batchExpiryDate;
	}

	@Column(name = "pack_desc", length = 50)
	public String getPackDesc() {
		return this.packDesc;
	}

	public void setPackDesc(String packDesc) {
		this.packDesc = packDesc;
	}

	@Column(name = "stk_quarantine_qty")
	public Long getStkQuarantineQty() {
		return this.stkQuarantineQty;
	}

	public void setStkQuarantineQty(Long stkQuarantineQty) {
		this.stkQuarantineQty = stkQuarantineQty;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
