package my.com.cmg.iwp.backend.model.integration;
// default package
// Generated May 23, 2013 12:39:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.IndexColumn;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * PhCurrentstkHdrsInt generated by hbm2java
 */
@Entity
@Table(name = "t_currentstk_hdrs_int")
@XmlRootElement(name="CurrentstkHdrsInt")
@JsonIgnoreProperties(ignoreUnknown=true)
public class CurrentstkHdrsInt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long stkLotIntNo;
	private String itemCode;
	private String stkItemGroup;
	private String drugCode;
	private String nondrugCode;
	private String brdCode;
	private BigDecimal unitPrice;
	private OutsourceOrderInt outsourceOrderInt;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private Set<CurrentstkDtlsInt> currentstkDtlsInts = new HashSet<CurrentstkDtlsInt>(0);

	public CurrentstkHdrsInt() {
	}

	public CurrentstkHdrsInt(long stkLotIntNo, String itemCode,
			String stkItemGroup, String brdCode, OutsourceOrderInt outsourceOrderInt,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.stkLotIntNo = stkLotIntNo;
		this.itemCode = itemCode;
		this.stkItemGroup = stkItemGroup;
		this.brdCode = brdCode;
		this.outsourceOrderInt = outsourceOrderInt;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public CurrentstkHdrsInt(long stkLotIntNo, String itemCode,
			String stkItemGroup, String drugCode, String nondrugCode, String brdCode,
			BigDecimal unitPrice, OutsourceOrderInt outsourceOrderInt, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, long createdBy, Date createdDate, long updatedBy,
			Date updatedDate, Set<CurrentstkDtlsInt> phCurrentstkDtlsInts) {
		this.stkLotIntNo = stkLotIntNo;
		this.itemCode = itemCode;
		this.stkItemGroup = stkItemGroup;
		this.drugCode = drugCode;
		this.nondrugCode = nondrugCode;
		this.brdCode = brdCode;
		this.unitPrice = unitPrice;
		this.outsourceOrderInt = outsourceOrderInt;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.currentstkDtlsInts = phCurrentstkDtlsInts;
	}

	@Id
	@SequenceGenerator(name="ph_current_stk_hdr_int_seq", sequenceName="t_currentstk_hdrs_int_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ph_current_stk_hdr_int_seq")
	@Column(name = "stk_lot_int_no", nullable = false)
	@JsonIgnore
	public long getStkLotIntNo() {
		return this.stkLotIntNo;
	}

	public void setStkLotIntNo(long stkLotIntNo) {
		this.stkLotIntNo = stkLotIntNo;
	}

	@Column(name = "item_code", nullable = false)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "stk_item_group", nullable = false, length = 20)
	public String getStkItemGroup() {
		return this.stkItemGroup;
	}

	public void setStkItemGroup(String stkItemGroup) {
		this.stkItemGroup = stkItemGroup;
	}

	@Column(name = "drug_code")
	public String getDrugCode() {
		return this.drugCode;
	}

	public void setDrugCode(String drugCode) {
		this.drugCode = drugCode;
	}

	@Column(name = "nondrug_code")
	public String getNondrugCode() {
		return this.nondrugCode;
	}

	public void setNondrugCode(String nondrugCode) {
		this.nondrugCode = nondrugCode;
	}

	@Column(name = "brd_code", nullable = false)
	public String getBrdCode() {
		return this.brdCode;
	}

	public void setBrdCode(String brdCode) {
		this.brdCode = brdCode;
	}

	@Column(name = "unit_price", precision = 15, scale = 4)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@ManyToOne
	@JoinColumn(name = "outsource_int_seqno", nullable = false)
	@JsonBackReference("CurrentstkHdrsOutsourceOrderInt")
	public OutsourceOrderInt getOutsourceOrderInt() {
		return this.outsourceOrderInt;
	}

	public void setOutsourceOrderInt(OutsourceOrderInt outsourceOrderInt) {
		this.outsourceOrderInt = outsourceOrderInt;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(mappedBy = "currentstkHdrsInt", cascade = CascadeType.ALL)
	@IndexColumn(name="stkdtls_int_seqno")
	@XmlElement
	@JsonManagedReference("CurrentstkDtlsInt")
	public Set<CurrentstkDtlsInt> getCurrentstkDtlsInts() {
		return this.currentstkDtlsInts;
	}

	public void setCurrentstkDtlsInts(Set<CurrentstkDtlsInt> currentstkDtlsInts) {
		this.currentstkDtlsInts = currentstkDtlsInts;
	}

}
