package my.com.cmg.iwp.backend.model.inventory.penalty;

// Generated May 21, 2015 10:21:47 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import my.com.cmg.iwp.maintenance.model.BaseEntity;
import my.com.cmg.iwp.maintenance.model.SecUser;
import my.com.cmg.iwp.webui.constant.RefCodeConstant;

/**
 * TPenaltyBatch generated by hbm2java
 */
@Entity
@Table(name = "T_PENALTY_BATCH")
@XmlRootElement(name = "PenaltyBatch")
@JsonIgnoreProperties(ignoreUnknown=true)
public class PenaltyBatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long penBatchSeqno;
	private PenaltyItem penaltyItem;
	private long penItemSeqno;
	private String batchNo;
	private Date batchExpDate;
	private Long qtyPku;
	private Double unitPrice;
	private Long recommendedDelayDays;
	private Long realDelayDays;
	private Double recommendedPenaltyAmt;
	private Double realPenaltyAmt;
	private Long rejectQty;
	private String remarks;
	private Double proposedPenaltyAmt;
	private Character minPayFlag = RefCodeConstant.BOOLEAN_TRUE;

	public PenaltyBatch() {
	}

	public PenaltyBatch(PenaltyItem penaltyItem, String batchNo, Date date) {
		setCreatedBy(penaltyItem.getUpdatedBy());
		setCreatedUser(penaltyItem.getUpdatedUser());
		setCreatedDate(new Date());
		setUpdatedBy(penaltyItem.getUpdatedBy());
		setUpdatedUser(penaltyItem.getUpdatedUser());
		setUpdatedDate(new Date());
		setActiveFlag(RefCodeConstant.ACTIVE_FLAG_TRUE);
		setPenaltyItem(penaltyItem);
		setBatchExpDate(date);
		setBatchNo(batchNo);
	}

	@Id
	@Column(name = "P_BATCH_SEQNO", unique = true, nullable = false)
	@SequenceGenerator(name = "T_PENALTY_BATCH_SEQ", sequenceName = "T_PENALTY_BATCH_SEQ", allocationSize  = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "T_PENALTY_BATCH_SEQ")
	public long getPenBatchSeqno() {
		return this.penBatchSeqno;
	}
	
	public void setPenBatchSeqno(long PGrandchildSeqno) {
		this.penBatchSeqno = PGrandchildSeqno;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="P_ITEM_SEQNO")
	@JsonManagedReference	
	public PenaltyItem getPenaltyItem() {
		return penaltyItem;
	}

	public void setPenaltyItem(PenaltyItem penaltyItem) {
		this.penaltyItem = penaltyItem;
	}

	@Column(name = "P_ITEM_SEQNO", precision = 22, scale = 0, insertable=false,updatable = false)
	public long getPenItemSeqno() {
		return this.penItemSeqno;
	}

	public void setPenItemSeqno(long PChildSeqno) {
		this.penItemSeqno = PChildSeqno;
	}

	@Column(name = "BATCH_NO", length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BATCH_EXP_DATE", length = 7)
	public Date getBatchExpDate() {
		return this.batchExpDate;
	}

	public void setBatchExpDate(Date batchExpDate) {
		this.batchExpDate = batchExpDate;
	}

	@Column(name = "QTY_PKU", precision = 22, scale = 0)
	public Long getQtyPku() {
		return this.qtyPku;
	}

	public void setQtyPku(Long qtyPku) {
		this.qtyPku = qtyPku;
	}

	@Column(name = "UNIT_PRICE", precision = 15)
	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "RECOMMENDED_DELAY_DAYS", precision = 22, scale = 0)
	public Long getRecommendedDelayDays() {
		return this.recommendedDelayDays;
	}

	public void setRecommendedDelayDays(Long recommendedDelayDays) {
		this.recommendedDelayDays = recommendedDelayDays;
	}

	@Column(name = "REAL_DELAY_DAYS", precision = 22, scale = 0)
	public Long getRealDelayDays() {
		return this.realDelayDays;
	}

	public void setRealDelayDays(Long realDelayDays) {
		this.realDelayDays = realDelayDays;
	}

	@Column(name = "RECOMMENDED_PENALTY_AMT", precision = 15)
	public Double getRecommendedPenaltyAmt() {
		return this.recommendedPenaltyAmt;
	}

	public void setRecommendedPenaltyAmt(Double recommendedPenaltyAmt) {
		this.recommendedPenaltyAmt = recommendedPenaltyAmt;
	}

	@Column(name = "REAL_PENALTY_AMT", precision = 15)
	public Double getRealPenaltyAmt() {
		return this.realPenaltyAmt;
	}

	public void setRealPenaltyAmt(Double realPenaltyAmt) {
		this.realPenaltyAmt = realPenaltyAmt;
	}

	@Column(name = "REJECT_QTY", precision = 22, scale = 0)
	public Long getRejectQty() {
		return this.rejectQty;
	}

	public void setRejectQty(Long rejectQty) {
		this.rejectQty = rejectQty;
	}

	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;

	private SecUser updatedUser;

	private SecUser createdUser;
	
	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3")
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4")
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag", nullable = false)
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", insertable = false, updatable = false)
	@JsonIgnore
	public SecUser getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(SecUser createdUser) {
		this.createdUser = createdUser;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by", insertable = false, updatable = false)
	@JsonIgnore
	public SecUser getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(SecUser updatedUser) {
		this.updatedUser = updatedUser;
	}
	
	@Column(name = "proposed_penalty_amt", precision = 11)
	public Double getProposedPenaltyAmt() {
		return proposedPenaltyAmt;
	}

	public void setProposedPenaltyAmt(Double proposedPenaltyAmt) {
		this.proposedPenaltyAmt = proposedPenaltyAmt;
	}
	
	@Column(name = "minpay_flag")
	public Character getMinPayFlag() {
		return minPayFlag;
	}

	public void setMinPayFlag(Character minPayFlag) {
		this.minPayFlag = minPayFlag;
	}
}
