package my.com.cmg.iwp.maintenance.model;

// Generated 15 Mar, 2012 1:28:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import my.com.cmg.iwp.webui.constant.RefCodeConstant;

/**
 * Frequency generated by hbm2java
 */
@Entity
@Table(name = "t_frequencies", uniqueConstraints = @UniqueConstraint(columnNames = "freq_code"))
public class Frequency implements java.io.Serializable {
	private static final long serialVersionUID = -6715255191996947481L;
	private long freqSeqno = Long.MIN_VALUE;
	private String freqCode;
	private String freqDesc;
	private String freqLocalDesc;
	private String freqEnglish;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private String type;
	private int noofadmin = 0;
	private String noofadminDurationType;
	private int intervalValue = 0;
	private String intervalDurationType;
	private Character scheduledYn;
	private String days;
	private Character mondayYN = 'N';
	private Character tuesdayYN = 'N';
	private Character wednesdayYN = 'N';
	private Character thursdayYN = 'N';
	private Character fridayYN = 'N';
	private Character saturdayYN = 'N';
	private Character sundayYN = 'N';
	private String MARType;
	private RegimenDays regimenDays;
	private Character hemodialysisYn = RefCodeConstant.BOOLEAN_FALSE;
	private Character isHd = RefCodeConstant.BOOLEAN_FALSE;
	private String hemoDialysisFreqCode;
	private Integer freqPerWeek;
	private Set<FrequencySchedule> frequencySchedules = new HashSet<FrequencySchedule>(
			0);

	private Set<DrugFrequency> drugFrequencies = new HashSet<DrugFrequency>(0);

	public Frequency() {
	}

	public Frequency(long freqSeqno, String freqCode, String freqDesc,
			long createBy, Date createDate, long updateBy, Date updateDate) {
		this.freqSeqno = freqSeqno;
		this.freqCode = freqCode;
		this.freqDesc = freqDesc;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
	}

	public Frequency(long freqSeqno, String freqCode, String freqDesc,
			String freqLocalDesc, long createBy, Date createDate,
			long updateBy, Date updateDate, int noofadmin,
			String noofadminDurationType, int intervalValue,
			String intervalDurationType, Character scheduledYn, String days,
			Set<FrequencySchedule> frequencySchedules,
			Set<DrugFrequency> drugFrequencies) {
		this.freqSeqno = freqSeqno;
		this.freqCode = freqCode;
		this.freqDesc = freqDesc;
		this.freqLocalDesc = freqLocalDesc;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
		this.noofadmin = noofadmin;
		this.noofadminDurationType = noofadminDurationType;
		this.intervalValue = intervalValue;
		this.intervalDurationType = intervalDurationType;
		this.scheduledYn = scheduledYn;
		this.days = days;
		// this.frequencySchedules = frequencySchedules;
		this.drugFrequencies = drugFrequencies;
	}

	@Id
	@Column(name = "freq_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "frequencySeqno", sequenceName = "t_frequencies_seq", allocationSize = 1)
	@GeneratedValue(generator = "frequencySeqno", strategy = GenerationType.SEQUENCE)
	public long getFreqSeqno() {
		return this.freqSeqno;
	}

	public void setFreqSeqno(long freqSeqno) {
		this.freqSeqno = freqSeqno;
	}

	@Column(name = "freq_code", unique = true, nullable = false, length = 15)
	public String getFreqCode() {
		return this.freqCode;
	}

	public void setFreqCode(String freqCode) {
		this.freqCode = freqCode;
	}

	@Column(name = "freq_desc", nullable = false, length = 250)
	public String getFreqDesc() {
		return this.freqDesc;
	}

	public void setFreqDesc(String freqDesc) {
		this.freqDesc = freqDesc;
	}

	@Column(name = "freq_local_desc", length = 250)
	public String getFreqLocalDesc() {
		return this.freqLocalDesc;
	}

	public void setFreqLocalDesc(String freqLocalDesc) {
		this.freqLocalDesc = freqLocalDesc;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createBy) {
		this.createdBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createDate) {
		this.createdDate = createDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updateBy) {
		this.updatedBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updateDate) {
		this.updatedDate = updateDate;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setNoofadmin(int noofadmin) {
		this.noofadmin = noofadmin;
	}

	@Column(name = "noofadmin")
	public int getNoofadmin() {
		return noofadmin;
	}

	public void setNoofadminDurationType(String noofadminDurationType) {
		this.noofadminDurationType = noofadminDurationType;
	}

	@Column(name = "noofadmin_duration_type", length = 10)
	public String getNoofadminDurationType() {
		return noofadminDurationType;
	}

	public void setIntervalValue(int intervalValue) {
		this.intervalValue = intervalValue;
	}

	@Column(name = "interval_value")
	public int getIntervalValue() {
		return intervalValue;
	}

	public void setIntervalDurationType(String intervalDurationType) {
		this.intervalDurationType = intervalDurationType;
	}

	@Column(name = "interval_duration_type", length = 10)
	public String getIntervalDurationType() {
		return intervalDurationType;
	}

	public void setScheduledYn(Character scheduledYn) {
		this.scheduledYn = scheduledYn;
	}

	@Column(name = "scheduled_yn", length = 1)
	public Character getScheduledYn() {
		return scheduledYn;
	}

	public void setDays(String days) {
		this.days = days;
	}

	@Column(name = "days", length = 60)
	public String getDays() {
		return days;
	}

	public void setFrequencySchedules(Set<FrequencySchedule> frequencySchedules) {
		this.frequencySchedules = frequencySchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frequency",cascade = CascadeType.ALL)
	public Set<FrequencySchedule> getFrequencySchedules() {
		return frequencySchedules;
	}

	public void setDrugFrequencies(Set<DrugFrequency> drugFrequencies) {
		this.drugFrequencies = drugFrequencies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frequency")
	public Set<DrugFrequency> getDrugFrequencies() {
		return drugFrequencies;
	}

	public void setFreqEnglish(String freqEnglish) {
		this.freqEnglish = freqEnglish;
	}

	@Column(name = "freq_english_desc ", length = 250)
	public String getFreqEnglish() {
		return freqEnglish;
	}

	public void setMondayYN(Character mondayYN) {
		this.mondayYN = mondayYN;
	}

	@Column(name = "monday_yn")
	public Character getMondayYN() {
		return mondayYN;
	}

	public void setTuesdayYN(Character tuesdayYN) {
		this.tuesdayYN = tuesdayYN;
	}

	@Column(name = "tuesday_yn")
	public Character getTuesdayYN() {
		return tuesdayYN;
	}

	public void setWednesdayYN(Character wednesdayYN) {
		this.wednesdayYN = wednesdayYN;
	}

	@Column(name = "wednesday_yn")
	public Character getWednesdayYN() {
		return wednesdayYN;
	}

	public void setThursdayYN(Character thursdayYN) {
		this.thursdayYN = thursdayYN;
	}

	@Column(name = "thursday_yn")
	public Character getThursdayYN() {
		return thursdayYN;
	}

	public void setFridayYN(Character fridayYN) {
		this.fridayYN = fridayYN;
	}

	@Column(name = "friday_yn")
	public Character getFridayYN() {
		return fridayYN;
	}

	public void setSaturdayYN(Character saturdayYN) {
		this.saturdayYN = saturdayYN;
	}

	@Column(name = "saturday_yn")
	public Character getSaturdayYN() {
		return saturdayYN;
	}

	public void setSundayYN(Character sundayYN) {
		this.sundayYN = sundayYN;
	}

	@Column(name = "sunday_yn")
	public Character getSundayYN() {
		return sundayYN;
	}

	@Column(name = "mar_type")
	public String getMARType() {
		return MARType;
	}

	public void setMARType(String mARType) {
		MARType = mARType;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "frequency",cascade = CascadeType.ALL)
	public RegimenDays getRegimenDays() {
		return regimenDays;
	}

	public void setRegimenDays(RegimenDays regimenDays) {
		this.regimenDays = regimenDays;
	}
	


	@Column(name="hemodialysis_yn")
	public Character getHemodialysisYn() {
		return hemodialysisYn;
	}

	public void setHemodialysisYn(Character hemodialysisYn) {
		this.hemodialysisYn = hemodialysisYn;
	}

	@Column(name="is_hd")
	public Character getIsHd() {
		return isHd;
	}

	public void setIsHd(Character isHd) {
		this.isHd = isHd;
	}

	@Column(name="hemodialysis_freq_code")
	public String getHemoDialysisFreqCode() {
		return hemoDialysisFreqCode;
	}

	public void setHemoDialysisFreqCode(String hemoDialysisFreqCode) {
		this.hemoDialysisFreqCode = hemoDialysisFreqCode;
	}

	@Column(name="freq_per_week")
	public Integer getFreqPerWeek() {
		return freqPerWeek;
	}

	public void setFreqPerWeek(Integer freqPerWeek) {
		this.freqPerWeek = freqPerWeek;
	}
}