package my.com.cmg.iwp.maintenance.model.report.stg;

// Generated 19 Feb, 2013 3:08:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PhBudgetBalanceStg generated by hbm2java
 */
@Entity
@Table(name = "t_budget_balance_stg")
public class BudgetBalanceStg implements java.io.Serializable {

	private long budgetbSeqno;
	private String voteCode;
	private String voteDescription;
	private String voteObjectCode;
	private Double pendingAmt;
	private Double liabilityAmt;
	private Double utilizedAmt;
	private Double actualBalance;
	private long createdBy;
	private String sessionId;
	private String clinicName;
	private Double transactionAmtFirst;
	private String budgetType;
	private BigDecimal virement;
	

	private Double transactionAmtAddition;
	private String nePVoteDesc;
	

	public BudgetBalanceStg() {
	}

	public BudgetBalanceStg(long budgetbSeqno, long createdBy) {
		this.budgetbSeqno = budgetbSeqno;
		this.createdBy = createdBy;
	}
	public BudgetBalanceStg(long budgetbSeqno, String voteCode, String voteDescription, String voteObjectCode,
			Double pendingAmt, Double liabilityAmt, Double utilizedAmt, Double actualBalance, long createdBy,
			String sessionId, String clinicName, Double transactionAmtFirst, String budgetType, BigDecimal virement,
			Double transactionAmtAddition) {
		super();
		this.budgetbSeqno = budgetbSeqno;
		this.voteCode = voteCode;
		this.voteDescription = voteDescription;
		this.voteObjectCode = voteObjectCode;
		this.pendingAmt = pendingAmt;
		this.liabilityAmt = liabilityAmt;
		this.utilizedAmt = utilizedAmt;
		this.actualBalance = actualBalance;
		this.createdBy = createdBy;
		this.sessionId = sessionId;
		this.clinicName = clinicName;
		this.transactionAmtFirst = transactionAmtFirst;
		this.budgetType = budgetType;
		this.virement = virement;
		this.transactionAmtAddition = transactionAmtAddition;
	}

	@Id
	@Column(name = "budgetb_seqno", unique = true, nullable = false)
	public long getBudgetbSeqno() {
		return this.budgetbSeqno;
	}

	public void setBudgetbSeqno(long budgetbSeqno) {
		this.budgetbSeqno = budgetbSeqno;
	}

	@Column(name = "vote_code", length = 33)
	public String getVoteCode() {
		return this.voteCode;
	}

	public void setVoteCode(String voteCode) {
		this.voteCode = voteCode;
	}

	@Column(name = "vote_description", length = 50)
	public String getVoteDescription() {
		return this.voteDescription;
	}

	public void setVoteDescription(String voteDescription) {
		this.voteDescription = voteDescription;
	}

	@Column(name = "vote_object_code", length = 6)
	public String getVoteObjectCode() {
		return this.voteObjectCode;
	}

	public void setVoteObjectCode(String voteObjectCode) {
		this.voteObjectCode = voteObjectCode;
	}

	@Column(name = "pending_amt", precision = 15, scale = 4)
	public Double getPendingAmt() {
		return this.pendingAmt;
	}

	public void setPendingAmt(Double pendingAmt) {
		this.pendingAmt = pendingAmt;
	}

	@Column(name = "liability_amt", precision = 15, scale = 4)
	public Double getLiabilityAmt() {
		return this.liabilityAmt;
	}

	public void setLiabilityAmt(Double liabilityAmt) {
		this.liabilityAmt = liabilityAmt;
	}

	@Column(name = "utilized_amt", precision = 15, scale = 4)
	public Double getUtilizedAmt() {
		return this.utilizedAmt;
	}

	public void setUtilizedAmt(Double utilizedAmt) {
		this.utilizedAmt = utilizedAmt;
	}

	@Column(name = "actual_balance", precision = 15, scale = 4)
	public Double getActualBalance() {
		return this.actualBalance;
	}

	public void setActualBalance(Double actualBalance) {
		this.actualBalance = actualBalance;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "session_id", length = 50)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name="clinic_name")
	public String getClinicName() {
		return clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}
	@Column(name = "transaction_amt_first", precision = 15, scale = 4)
	public Double getTransactionAmtFirst() {
		return transactionAmtFirst;
	}

	public void setTransactionAmtFirst(Double transactionAmtFirst) {
		this.transactionAmtFirst = transactionAmtFirst;
	}
	@Column(name = "transaction_amt_addition", precision = 15, scale = 4)
	public Double getTransactionAmtAddition() {
		return transactionAmtAddition;
	}

	public void setTransactionAmtAddition(Double transactionAmtAddition) {
		this.transactionAmtAddition = transactionAmtAddition;
	}
	
	@Column(name="budget_type")
	public String getBudgetType() {
		return budgetType;
	}

	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}
	@Column(name="virement" , precision = 15, scale = 4)
	public BigDecimal getVirement() {
		return virement;
	}

	public void setVirement(BigDecimal virement) {
		this.virement = virement;
	}
	
	@Column(name="nep_vote")
	public String getNePVoteDesc() {
		return nePVoteDesc;
	}

	public void setNePVoteDesc(String nePVoteDesc) {
		this.nePVoteDesc = nePVoteDesc;
	}
}
