package my.com.cmg.iwp.maintenance.model;

// Generated Jul 6, 2012 5:39:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;

/**
 * Discipline generated by hbm2java
 */
@Entity
@Table(name = "t_disciplines")
public class Discipline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4108046849037816561L;
	private long disciplineSeqno = Long.MIN_VALUE;
	private String disciplineCode;
	private String disciplineName;
	private String remarks;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private Set<SubDiscipline> subDisciplineses = new HashSet<SubDiscipline>(0);

	public Discipline() {
	}

	public Discipline(long disciplineSeqno, String disciplineCode,
			String disciplineName, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate) {
		this.disciplineSeqno = disciplineSeqno;
		this.disciplineCode = disciplineCode;
		this.disciplineName = disciplineName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public Discipline(long disciplineSeqno, String disciplineCode,
			String disciplineName, String remarks, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, Character activeFlag, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.disciplineSeqno = disciplineSeqno;
		this.disciplineCode = disciplineCode;
		this.disciplineName = disciplineName;
		this.remarks = remarks;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;

	}

	@Id
	@Column(name = "discipline_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "discipline_seqno", sequenceName = "t_disciplines_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "discipline_seqno")
	public long getDisciplineSeqno() {
		return this.disciplineSeqno;
	}

	public void setDisciplineSeqno(long disciplineSeqno) {
		this.disciplineSeqno = disciplineSeqno;
	}

	@Column(name = "discipline_code", nullable = false, length = 20)
	public String getDisciplineCode() {
		return this.disciplineCode;
	}

	public void setDisciplineCode(String disciplineCode) {
		this.disciplineCode = disciplineCode;
	}

	@Column(name = "discipline_name", nullable = false, length = 100)
	public String getDisciplineName() {
		return this.disciplineName;
	}

	public void setDisciplineName(String disciplineName) {
		this.disciplineName = disciplineName;
	}

	@Column(name = "remarks", length = 200)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discipline", cascade = CascadeType.ALL)
	public Set<SubDiscipline> getSubDisciplineses() {
		return this.subDisciplineses;
	}

	public void setSubDisciplineses(Set<SubDiscipline> subDisciplineses) {
		this.subDisciplineses = subDisciplineses;
	}
}
