package my.com.cmg.iwp.maintenance.model.report.stg;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhBudgetMovementStg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_budget_summary_stg")
public class BudgetSummaryStg implements java.io.Serializable {

	private long budgetSummarySeqno;
	private String voteCode;
	private String transactionNo;
	private String transactionType;
	private String budgetType;
	private String warrantReferenceNo;
	private String voteDesc;
	private Date createdDate;
	private Long createdBy;
	private String remarks;
	private Double amount;
	private Double balanceAmount;
	private Long stgCreatedBy;
	private String objectCode;
	private String fullName;
	private String clinicName;
	private String nePVoteDesc;

	public BudgetSummaryStg() {
	}

	public BudgetSummaryStg(long budgetSummarySeqno) {
		this.budgetSummarySeqno = budgetSummarySeqno;
	}

	public BudgetSummaryStg(long budgetSummarySeqno, String voteCode, String transactionNo,
			String transactionType, String budgetType, String warrantReferenceNo, String voteDesc, Date createdDate,
			Long createdBy, String remarks, Double amount, Double balanceAmount, Long stgCreatedBy,
			String objectCode, String fullName, String clinicName) {
		super();
		this.budgetSummarySeqno = budgetSummarySeqno;
		this.voteCode = voteCode;
		this.transactionNo = transactionNo;
		this.transactionType = transactionType;
		this.budgetType = budgetType;
		this.warrantReferenceNo = warrantReferenceNo;
		this.voteDesc = voteDesc;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.remarks = remarks;
		this.amount = amount;
		this.balanceAmount = balanceAmount;
		this.stgCreatedBy = stgCreatedBy;
		this.objectCode = objectCode;
		this.fullName = fullName; 
	}

	@Id
	@Column(name = "budget_summary_seqno", unique = true, nullable = false)
	public long getBudgetSummarySeqno() {
		return budgetSummarySeqno;
	}

	public void setBudgetSummarySeqno(long budgetSummarySeqno) {
		this.budgetSummarySeqno = budgetSummarySeqno;
	}

	@Column(name = "vote_code", length = 33)
	public String getVoteCode() {
		return voteCode;
	}

	public void setVoteCode(String voteCode) {
		this.voteCode = voteCode;
	}

	@Column(name = "transaction_no", length = 20)
	public String getTransactionNo() {
		return transactionNo;
	}

	public void setTransactionNo(String transactionNo) {
		this.transactionNo = transactionNo;
	}

	@Column(name = "transaction_type", length = 15)
	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "budget_type", length = 13)
	public String getBudgetType() {
		return budgetType;
	}

	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}

	@Column(name = "warrant_reference_no", length = 40)
	public String getWarrantReferenceNo() {
		return warrantReferenceNo;
	}

	public void setWarrantReferenceNo(String warrantReferenceNo) {
		this.warrantReferenceNo = warrantReferenceNo;
	}

	@Column(name = "vote_desc", length = 50)
	public String getVoteDesc() {
		return voteDesc;
	}

	public void setVoteDesc(String voteDesc) {
		this.voteDesc = voteDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 13)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = false)
	public Long getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "amount", precision = 15, scale = 4)
	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "balance_amount", precision = 15, scale = 4)
	public Double getBalanceAmount() {
		return balanceAmount;
	}

	public void setBalanceAmount(Double balanceAmount) {
		this.balanceAmount = balanceAmount;
	}

	@Column(name = "stg_created_by", nullable = false)
	public Long getStgCreatedBy() {
		return stgCreatedBy;
	}

	public void setStgCreatedBy(Long stgCreatedBy) {
		this.stgCreatedBy = stgCreatedBy;
	}
	
	@Column(name = "object_code", length = 50)
	public String getObjectCode() {
		return objectCode;
	}

	public void setObjectCode(String objectCode) {
		this.objectCode = objectCode;
	}

	@Column(name = "full_name", length = 75)
	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name="clinic_name")
	public String getClinicName() {
		return clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}


	@Column(name="nep_vote")
	public String getNePVoteDesc() {
		return nePVoteDesc;
	}

	public void setNePVoteDesc(String nePVoteDesc) {
		this.nePVoteDesc = nePVoteDesc;
	}

	

}
