package my.com.cmg.iwp.maintenance.model;

// Generated Jun 4, 2012 5:32:11 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DosageForm generated by hbm2java
 */
@Entity
@Table(name = "t_dosage_forms", uniqueConstraints = @UniqueConstraint(columnNames = "dosage_code"))
public class DosageForm implements java.io.Serializable {
	private static final long serialVersionUID = 2708719911387758602L;
	private long dosageSeqno = Long.MIN_VALUE;
	private String dosageCode;
	private String dosageDesc;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createBy;
	private Date createDate;
	private long updateBy;
	private Date updateDate;
	private Character dosageStatus;

	public DosageForm() {
	}

	public DosageForm(long dosageSeqno, String dosageCode, String dosageDesc,
			long createBy, Date createDate, long updateBy, Date updateDate) {
		this.dosageSeqno = dosageSeqno;
		this.dosageCode = dosageCode;
		this.dosageDesc = dosageDesc;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	public DosageForm(long dosageSeqno, String dosageCode, String dosageDesc,
			String parameter1, String parameter2, BigDecimal parameter3,
			BigDecimal parameter4, Date parameter5, Character activeFlag,
			long createBy, Date createDate, long updateBy, Date updateDate,
			Character dosageStatus) {
		this.dosageSeqno = dosageSeqno;
		this.dosageCode = dosageCode;
		this.dosageDesc = dosageDesc;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.dosageStatus = dosageStatus;
	}

	@Id
	@Column(name = "dosage_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "dosageSEQ", sequenceName = "t_dosage_forms_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "dosageSEQ")
	public long getDosageSeqno() {
		return this.dosageSeqno;
	}

	public void setDosageSeqno(long dosageSeqno) {
		this.dosageSeqno = dosageSeqno;
	}

	@Column(name = "dosage_code", unique = true, nullable = false, length = 35)
	public String getDosageCode() {
		return this.dosageCode;
	}

	public void setDosageCode(String dosageCode) {
		this.dosageCode = dosageCode;
	}

	@Column(name = "dosage_desc", nullable = false, length = 300)
	public String getDosageDesc() {
		return this.dosageDesc;
	}

	public void setDosageDesc(String dosageDesc) {
		this.dosageDesc = dosageDesc;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(long createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(long updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "dosage_status", length = 1)
	public Character getDosageStatus() {
		return this.dosageStatus;
	}

	public void setDosageStatus(Character dosageStatus) {
		this.dosageStatus = dosageStatus;
	}
}