package my.com.cmg.iwp.maintenance.model;
// default package
// Generated Oct 15, 2012 3:51:37 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * PhCounsellingMaterial generated by hbm2java
 */
@Entity
@Table(name = "t_counselling_material")
public class CounsellingMaterial {

	private long counsellingMaterialSeqno;
	private String code;
	private String codeDesc;
	private String materialType;
	private String documentIndexing;
	private String documentVersionNo;
	private String modificFromPrevVersion;
	private byte[] attachDocument;
	private Long personUploadingDocument;
	private Date dateProduced;
	private Date dateUploaded;
	private Character originalDocument;
	private Character revisedDocument;
	private Long createdBy;
	private Date createdDate;
	private SecUser createdUser;
	private Long updatedBy;
	private Date updatedDate;
	private SecUser updatedUser;
	public CounsellingMaterial() {
	}

	public CounsellingMaterial(long counsellingMaterialSeqno, long createdBy,
			Date createdDate, long updatedBy, Date updatedDate) {
		this.counsellingMaterialSeqno = counsellingMaterialSeqno;
	}

	public CounsellingMaterial(long counsellingMaterialSeqno, String code,
			String materialType, String documentIndexing,
			String documentVersionNo, String modificationFromPreviousVersion,
			byte[] attachDocument, Long personUploadingDocument,
			Date dateProduced, Date dateUploaded, Character originalDocument,
			Character revisedDocument, String parameter1, String parameter2,
			BigDecimal parameter3, BigDecimal parameter4, Date parameter5,
			Character activeFlag, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate) {
		this.counsellingMaterialSeqno = counsellingMaterialSeqno;
		this.code = code;
		this.materialType = materialType;
		this.documentIndexing = documentIndexing;
		this.documentVersionNo = documentVersionNo;
		this.modificFromPrevVersion = modificationFromPreviousVersion;
		this.attachDocument = attachDocument;
		this.personUploadingDocument = personUploadingDocument;
		this.dateProduced = dateProduced;
		this.dateUploaded = dateUploaded;
		this.originalDocument = originalDocument;
		this.revisedDocument = revisedDocument;
	}

	
	@Id
	@SequenceGenerator(name="t_counselling_material_seqno", sequenceName="t_counselling_material_seq", allocationSize = 1)
	@GeneratedValue(generator="t_counselling_material_seqno")
	@Column(name = "counselling_material_seqno", unique = true, nullable = false)
	public long getCounsellingMaterialSeqno() {
		return this.counsellingMaterialSeqno;
	}

	public void setCounsellingMaterialSeqno(long counsellingMaterialSeqno) {
		this.counsellingMaterialSeqno = counsellingMaterialSeqno;
	}

	@Column(name = "counselling_material_code", length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "material_type", length = 30)
	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	@Column(name = "document_indexing", length = 30)
	public String getDocumentIndexing() {
		return this.documentIndexing;
	}

	public void setDocumentIndexing(String documentIndexing) {
		this.documentIndexing = documentIndexing;
	}

	@Column(name = "document_version_no", length = 30)
	public String getDocumentVersionNo() {
		return this.documentVersionNo;
	}

	public void setDocumentVersionNo(String documentVersionNo) {
		this.documentVersionNo = documentVersionNo;
	}

	@Column(name = "modific_from_prev_version", length = 100)
	public String getModificFromPrevVersion() {
		return this.modificFromPrevVersion;
	}

	public void setModificFromPrevVersion(
			String modificFromPrevVersion) {
		this.modificFromPrevVersion = modificFromPrevVersion;
	}

	@Column(name = "attach_document")
	public byte[] getAttachDocument() {
		return this.attachDocument;
	}

	public void setAttachDocument(byte[] attachDocument) {
		this.attachDocument = attachDocument;
	}

	@Column(name = "person_uploading_document")
	public Long getPersonUploadingDocument() {
		return this.personUploadingDocument;
	}

	public void setPersonUploadingDocument(Long personUploadingDocument) {
		this.personUploadingDocument = personUploadingDocument;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_produced", length = 13)
	public Date getDateProduced() {
		return this.dateProduced;
	}

	public void setDateProduced(Date dateProduced) {
		this.dateProduced = dateProduced;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_uploaded", length = 13)
	public Date getDateUploaded() {
		return this.dateUploaded;
	}

	public void setDateUploaded(Date dateUploaded) {
		this.dateUploaded = dateUploaded;
	}

	@Column(name = "original_document")
	public Character getOriginalDocument() {
		return this.originalDocument;
	}

	public void setOriginalDocument(Character originalDocument) {
		this.originalDocument = originalDocument;
	}

	@Column(name = "revised_document")
	public Character getRevisedDocument() {
		return this.revisedDocument;
	}

	public void setRevisedDocument(Character revisedDocument) {
		this.revisedDocument = revisedDocument;
	}

	@Column(name = "counselling_material_desc", length = 100)
	public String getCodeDesc() {
		return codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	@Column(name = "created_by", nullable = false)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", insertable = false, updatable = false)
	@JsonIgnore
	public SecUser getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(SecUser createdUser) {
		this.createdUser = createdUser;
	}

	@Column(name = "updated_by", nullable = false)
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by", insertable = false, updatable = false)
	@JsonIgnore
	public SecUser getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(SecUser updatedUser) {
		this.updatedUser = updatedUser;
	}
}
