package my.com.cmg.iwp.backend.model.integration.rp;
// default package
// Generated Jan 21, 2013 12:36:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * DispenseRpBatchInt generated by hbm2java
 */
@Entity
@Table(name = "t_dispense_rp_batch_int")
@JsonIgnoreProperties(ignoreUnknown=true)
public class DispenseRpBatchInt  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long rpBatchIntSeqno;
	private String batchNo;
//	private BigDecimal availableQty = BigDecimal.ZERO;
	private BigDecimal allocatedQty = BigDecimal.ZERO;
	private Date expiryDate;	
//	private Double availableActivity = 0d;
	private Double allocatedActivity = 0d;
	private Double allocatedActivityQty = 0d;	
	private Double allocatedVolume = 0d;	
	private String allocatedVolumeUom;
	private long orderRpIntSeqno;
	private OrderRpInt orderRpInt;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
									
	public DispenseRpBatchInt() {
	}


	
	@Id
	@SequenceGenerator(name="ph_dispense_rp_batch_seq", sequenceName="t_dispense_rp_batch_int_seq", allocationSize=1 )
	@GeneratedValue(generator="ph_dispense_rp_batch_seq")
	@Column(name = "rp_batch_int_seqno", unique = true, nullable = false)
	@JsonIgnore
	public long getRpBatchIntSeqno() {
		return this.rpBatchIntSeqno;
	}

	public void setRpBatchIntSeqno(long rpBatchIntSeqno) {
		this.rpBatchIntSeqno = rpBatchIntSeqno;
	}

	@Column(name = "batch_no")
	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}
	
	/*@Column(name = "available_qty", precision = 131089, scale = 0)
	public BigDecimal getAvailableQty() {
		return this.availableQty;
	}

	public void setAvailableQty(BigDecimal availableQty) {
		this.availableQty = availableQty;
	}*/

	@Column(name = "allocated_qty", precision = 131089, scale = 0)
	public BigDecimal getAllocatedQty() {
		return this.allocatedQty;
	}

	public void setAllocatedQty(BigDecimal allocatedQty) {
		this.allocatedQty = allocatedQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 29)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	/*@Column(name = "available_activity", precision = 12, scale = 4)
	public Double getAvailableActivity() {
		return availableActivity;
	}

	public void setAvailableActivity(Double availableActivity) {
		this.availableActivity = availableActivity;
	}*/

	@Column(name = "allocated_activity", precision = 12, scale = 4)
	public Double getAllocatedActivity() {
		return allocatedActivity;
	}

	public void setAllocatedActivity(Double allocatedActivity) {
		this.allocatedActivity = allocatedActivity;
	}

	@Column(name = "allocated_volume")
	public Double getAllocatedVolume() {
		return allocatedVolume;
	}

	public void setAllocatedVolume(Double allocatedVolume) {
		this.allocatedVolume = allocatedVolume;
	}

	@Column(name = "allocated_volume_uom")	
	public String getAllocatedVolumeUom() {
		return allocatedVolumeUom;
	}

	public void setAllocatedVolumeUom(String allocatedVolumeuom) {
		this.allocatedVolumeUom = allocatedVolumeuom;
	}

	@Column(name = "allocated_activity_qty")
	public Double getAllocatedActivityQty() {
		return allocatedActivityQty;
	}

	public void setAllocatedActivityQty(Double allocatedActivityQty) {
		this.allocatedActivityQty = allocatedActivityQty;
	}

	@Column(name = "order_rp_int_seqno", insertable = false, updatable = false)
	public long getOrderRpIntSeqno() {
		return orderRpIntSeqno;
	}

	public void setOrderRpIntSeqno(long orderRpIntSeqno) {
		this.orderRpIntSeqno = orderRpIntSeqno;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name="order_rp_int_seqno", nullable = false)
	@JsonBackReference("RpOutsourceOrderInt")
	public OrderRpInt getOrderRpInt() {
		return orderRpInt;
	}

	public void setOrderRpInt(OrderRpInt orderRpInt) {
		this.orderRpInt = orderRpInt;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}
