package my.com.cmg.iwp.backend.model.inventory.penalty;

// Generated May 21, 2015 10:21:47 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import my.com.cmg.iwp.maintenance.model.SecUser;
import my.com.cmg.iwp.webui.constant.RefCodeConstant;
import my.com.cmg.iwp.webui.inventory.penalty.PenaltyConstants;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TPenaltyVerification generated by hbm2java
 */
@Entity
@Table(name = "T_PENALTY_VERIFICATION_HDR")
@JsonIgnoreProperties(ignoreUnknown=true)
public class PenaltyVerificationHdr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long verifyHdrSeqno;
	private String verifyCode;
	private char lpoStatus;
	private String lpoNo;
	private String otherKey;
	private String hospitalCode;
	private String ptjCode;
	private String supplierCode;
	private String status;
	private String remarks;	
	private Date verifiedDate;
	private SecUser verifyByUser;
	private Long verifyBy;
	private Double amount;
	private Set<PenaltyVerificationDtl> penaltyVerificationDtls = new HashSet<PenaltyVerificationDtl>(0);
	private Set<PenaltyPayment> penaltyPayments = new HashSet<PenaltyPayment>(0);
	private String sendFlag;

	private String trxNumber;
	private Character withoutLPOYn = RefCodeConstant.BOOLEAN_FALSE; 
	
	private String createdUserName;
	private String updatedUserName;
	
	
	public PenaltyVerificationHdr() {
	}

	public PenaltyVerificationHdr(long TPenaltyVerifySeqno,
			String TPenaltyVerifyCd, char TLpoStatus, String TStatus,
			String TTransactionNumber, Long verifyBy,
			 long createdBy,
			long updatedBy, char activeFlag) {
		this.verifyHdrSeqno = TPenaltyVerifySeqno;
		this.verifyCode = TPenaltyVerifyCd;
		this.lpoStatus = TLpoStatus;
		this.status = TStatus;
		this.verifyBy = verifyBy;
		
	}

	

	public PenaltyVerificationHdr(SecUser loginUser) {
		setCreatedBy( loginUser.getId());
		setCreatedUser(loginUser);
		setCreatedUserName(loginUser.getUsrName());
		this.createdDate = new Date();
		setUpdatedBy(loginUser.getId());
		setUpdatedUser(loginUser);
		setUpdatedUserName(loginUser.getUsrName());
		this.updatedDate = new Date();
		
		setActiveFlag( RefCodeConstant.ACTIVE_FLAG_TRUE);
		setStatus( PenaltyConstants.PENALTY_VERIFICATION_STATUS_OPEN);
	}

	@Id
	@Column(name = "T_PENALTY_VERIFY_SEQNO", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "T_PENALTY_VERIFICATION_HDR_SEQ", sequenceName = "T_PENALTY_VERIFICATION_HDR_SEQ", allocationSize  = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "T_PENALTY_VERIFICATION_HDR_SEQ")
	public long getVerifyHdrSeqno() {
		return this.verifyHdrSeqno;
	}

	public void setVerifyHdrSeqno(long TPenaltyVerifySeqno) {
		this.verifyHdrSeqno = TPenaltyVerifySeqno;
	}

	@Column(name = "T_PENALTY_VERIFY_CD", nullable = false, length = 100)
	public String getVerifyCode() {
		return this.verifyCode;
	}

	public void setVerifyCode(String TPenaltyVerifyCd) {
		this.verifyCode = TPenaltyVerifyCd;
	}

	@Column(name = "T_LPO_STATUS", nullable = false, length = 1)
	public char getLpoStatus() {
		return this.lpoStatus;
	}

	public void setLpoStatus(char TLpoStatus) {
		this.lpoStatus = TLpoStatus;
	}

	@Column(name = "T_LPO_NO", length = 100)
	public String getLpoNo() {
		return this.lpoNo;
	}

	public void setLpoNo(String TLpoKey) {
		this.lpoNo = TLpoKey;
	}

	@Column(name = "T_OTHER_KEY", length = 200)
	public String getOtherKey() {
		return this.otherKey;
	}

	public void setOtherKey(String TOtherKey) {
		this.otherKey = TOtherKey;
	}

	@Column(name = "T_HOSPITAL_CODE", length = 200)
	public String getHospitalCode() {
		return this.hospitalCode;
	}

	public void setHospitalCode(String THospitalCode) {
		this.hospitalCode = THospitalCode;
	}

	@Column(name = "T_PTJ_CODE", length = 200)
	public String getPtjCode() {
		return this.ptjCode;
	}

	public void setPtjCode(String TPtjCode) {
		this.ptjCode = TPtjCode;
	}

	@Column(name = "T_SUPPLIER_CODE", length = 200)
	public String getSupplierCode() {
		return this.supplierCode;
	}

	public void setSupplierCode(String TSupplierCode) {
		this.supplierCode = TSupplierCode;
	}

	@Column(name = "T_STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String TStatus) {
		this.status = TStatus;
	}

	@Column(name = "T_REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String TRemarks) {
		this.remarks = TRemarks;
	}
	
	@Column(name = "T_TRANSACTION_NUMBER", length = 1000)
	public String getTrxNumber() {
		return this.trxNumber;
	}

	public void setTrxNumber(String trxNumber) {
		this.trxNumber = trxNumber;
	}
	
	
	@Temporal(TemporalType.DATE)
	@Column(name = "VERIFIED_DATE")
	public Date getVerifiedDate() {
		return this.verifiedDate;
	}

	public void setVerifiedDate(Date verifiedDate) {
		this.verifiedDate = verifiedDate;
	}
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="VERIFY_BY")
	public SecUser getVerifyByUser() {
		return verifyByUser;
	}

	public void setVerifyByUser(SecUser verifyByUser) {
		this.verifyByUser = verifyByUser;
	}

	@Column(name = "VERIFY_BY", insertable=false, updatable=false)
	public Long getVerifyBy() {
		return this.verifyBy;
	}

	public void setVerifyBy(Long verifyBy) {
		this.verifyBy = verifyBy;
	}

	@Column(name = "T_AMOUNT", precision = 15)
	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "penaltyVerificationHdr", cascade = CascadeType.ALL)
	@JsonManagedReference
	public Set<PenaltyVerificationDtl> getPenaltyVerificationDtls() {
		return penaltyVerificationDtls;
	}

	public void setPenaltyVerificationDtls(Set<PenaltyVerificationDtl> penaltyVerificationDtls) {
		this.penaltyVerificationDtls = penaltyVerificationDtls;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "penaltyVerificationHdr", cascade = CascadeType.ALL)
	@JsonBackReference
	public Set<PenaltyPayment> getPenaltyPayments() {
		return penaltyPayments;
	}

	public void setPenaltyPayments(Set<PenaltyPayment> penaltyPayments) {
		this.penaltyPayments = penaltyPayments;
	}
	
	@Column(name = "CREATED_USER_NAME", length = 101)
	public String getCreatedUserName() {
		return createdUserName;
	}

	public void setCreatedUserName(String createdUserName) {
		this.createdUserName = createdUserName;
	}
	
	@Column(name = "UPDATED_USER_NAME", length = 101)
	public String getUpdatedUserName() {
		return updatedUserName;
	}

	public void setUpdatedUserName(String updatedUserName) {
		this.updatedUserName = updatedUserName;
	}
	
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;

	private SecUser updatedUser;

	private SecUser createdUser;
	
	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3")
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4")
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag", nullable = false)
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", insertable = false, updatable = false)
	@JsonIgnore
	public SecUser getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(SecUser createdUser) {
		this.createdUser = createdUser;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by", insertable = false, updatable = false)
	@JsonIgnore
	public SecUser getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(SecUser updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Column(name = "WITHOUT_LPO_YN")
	public Character getWithoutLPOYn() {
		return withoutLPOYn;
	}

	public void setWithoutLPOYn(Character withoutLPOYn) {
		this.withoutLPOYn = withoutLPOYn;
	}
	
	@Column(name = "send_flag")
	public String getSendFlag() {
		return sendFlag;
	}

	public void setSendFlag(String sendFlag) {
		this.sendFlag = sendFlag;
	}
	
	
}
