package my.com.cmg.iwp.maintenance.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "t_departments", uniqueConstraints = @UniqueConstraint(columnNames = "dept_code"))
public class Department implements java.io.Serializable {
	private static final long serialVersionUID = -75089047327233605L;
	private long deptSeqno = Long.MIN_VALUE;
	private String deptCode;
	private String deptDesc;
	private String expireCriteria;
	private Character activeFlag = 'A';
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private String smrpDeptCode;

	public Department() {
	}

	public Department(long deptSeqno, String deptCode, long createBy,
			Date createDate, long updateBy, Date updateDate) {
		this.deptSeqno = deptSeqno;
		this.deptCode = deptCode;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
	}

	public Department(long deptSeqno, String deptCode, String deptDesc,
			String expireCriteria, long createBy, Date createDate,
			long updateBy, Date updateDate) {
		this.deptSeqno = deptSeqno;
		this.deptCode = deptCode;
		this.deptDesc = deptDesc;
		this.expireCriteria = expireCriteria;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
	}

	@Id
	@Column(name = "dept_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "deptSEQ", sequenceName = "t_departments_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "deptSEQ")
	public long getDeptSeqno() {
		return this.deptSeqno;
	}

	public void setDeptSeqno(long deptSeqno) {
		this.deptSeqno = deptSeqno;
	}

	@Column(name = "dept_code", unique = true, nullable = false, length = 10)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "dept_desc", length = 50)
	public String getDeptDesc() {
		return this.deptDesc;
	}

	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	@Column(name = "expire_criteria", length = 1)
	public String getExpireCriteria() {
		return this.expireCriteria;
	}

	public void setExpireCriteria(String expireCriteria) {
		this.expireCriteria = expireCriteria;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_by")
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createBy) {
		this.createdBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createDate) {
		this.createdDate = createDate;
	}

	@Column(name = "updated_by")
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updateBy) {
		this.updatedBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updateDate) {
		this.updatedDate = updateDate;
	}

	@Column(name = "smrp_dept_code", length = 29)
	public String getSmrpDeptCode() {
		return smrpDeptCode;
	}

	public void setSmrpDeptCode(String smrpDeptCode) {
		this.smrpDeptCode = smrpDeptCode;
	}
}
