package my.com.cmg.iwp.maintenance.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrugFrequency generated by hbm2java
 */
@Entity
@Table(name = "t_drug_frequencies")
public class DrugFrequency implements java.io.Serializable {
	private static final long serialVersionUID = -4999833523806822325L;
	private long drugFreqSeqno = Long.MIN_VALUE;
	private Drug drug;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private Character activeFlag = 'A';
	private Frequency frequency;
	private Character defaultFrequencyYn = 'N';
	private String guidelineInfo;
	private Character normalYn;
	private Character ivYn;
	private Character pnYn;
	private Character cdrYn;

	public DrugFrequency() {
	}

	public DrugFrequency(long drugFreqSeqno, long createBy, Date createDate,
			long updateBy, Date updateDate) {
		this.drugFreqSeqno = drugFreqSeqno;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
	}

	public DrugFrequency(long drugFreqSeqno, Drug drug, long createBy,
			Date createDate, long updateBy, Date updateDate, String parameter1,
			String parameter2, BigDecimal parameter3, BigDecimal parameter4,
			Date parameter5, Character activeFlag) {
		this.drugFreqSeqno = drugFreqSeqno;
		this.drug = drug;
		this.createdBy = createBy;
		this.createdDate = createDate;
		this.updatedBy = updateBy;
		this.updatedDate = updateDate;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.activeFlag = activeFlag;
	}

	@Id
	@Column(name = "drug_freq_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "drugFreqSEQ", sequenceName = "t_drug_frequencies_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "drugFreqSEQ")
	public long getDrugFreqSeqno() {
		return this.drugFreqSeqno;
	}

	public void setDrugFreqSeqno(long drugFreqSeqno) {
		this.drugFreqSeqno = drugFreqSeqno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_seqno")
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createBy) {
		this.createdBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createDate) {
		this.createdDate = createDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updateBy) {
		this.updatedBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updateDate) {
		this.updatedDate = updateDate;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "freq_seqno", nullable = false)
	public Frequency getFrequency() {
		return frequency;
	}

	public void setFrequency(Frequency frequency) {
		this.frequency = frequency;
	}

	public void setDefaultFrequencyYn(Character defaultFrequencyYn) {
		this.defaultFrequencyYn = defaultFrequencyYn;
	}

	@Column(name = "defaultfrequency_yn_hq")
	public Character getDefaultFrequencyYn() {
		return defaultFrequencyYn;
	}
	
	@Column(name = "guideline_info")
	public String getGuidelineInfo() {
		return guidelineInfo;
	}

	public void setGuidelineInfo(String guidelineInfo) {
		this.guidelineInfo = guidelineInfo;
	}

	@Column(name="normal_yn")
	public Character getNormalYn() {
		return normalYn;
	}

	public void setNormalYn(Character normalYn) {
		this.normalYn = normalYn;
	}

	@Column(name="iv_yn")
	public Character getIvYn() {
		return ivYn;
	}

	public void setIvYn(Character ivYn) {
		this.ivYn = ivYn;
	}

	@Column(name="pn_yn")
	public Character getPnYn() {
		return pnYn;
	}

	public void setPnYn(Character pnYn) {
		this.pnYn = pnYn;
	}

	@Column(name="cdr_yn")
	public Character getCdrYn() {
		return cdrYn;
	}

	public void setCdrYn(Character cdrYn) {
		this.cdrYn = cdrYn;
	}	
}