package my.com.cmg.iwp.maintenance.model;

// Generated Mar 22, 2012 1:22:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ItemAccumulative generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_item_accumulatives")
public class ItemAccumulative implements java.io.Serializable {

	private long itemSeqno = Long.MIN_VALUE;
	private Item item;
	private Integer itemYtdIssueQty;
	private Integer itemYtdReturnQty;
	private Integer itemYtdCondemnQty;
	private Integer itemYtdOrderQty;
	private BigDecimal itemYtdOrderAmt;
	private BigDecimal itemCumOrderAmt;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;

	private Integer itemYtdRecptQtyPku;
	private Integer itemYtdRecptQtySku;
	private Integer itemYtdPurQty;
	private BigDecimal itemYtdPurAmt;
	private BigDecimal itemYtdRecptAmt;

	public ItemAccumulative() {
	}

	public ItemAccumulative(Item item, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate) {
		this.item = item;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public ItemAccumulative(Item item, Integer itemYtdRecptQty,
			Integer itemYtdIssueQty, Integer itemYtdReturnQty,
			Integer itemYtdCondemnQty, Integer itemYtdOrderQty,
			BigDecimal itemYtdOrderAmt, BigDecimal itemCumOrderAmt,
			long createdBy, Date createdDate, long updatedBy, Date updatedDate) {
		this.item = item;
		// this.itemYtdRecptQty = itemYtdRecptQty;
		this.itemYtdIssueQty = itemYtdIssueQty;
		this.itemYtdReturnQty = itemYtdReturnQty;
		this.itemYtdCondemnQty = itemYtdCondemnQty;
		this.itemYtdOrderQty = itemYtdOrderQty;
		this.itemYtdOrderAmt = itemYtdOrderAmt;
		this.itemCumOrderAmt = itemCumOrderAmt;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "item"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "item_seqno")
	public long getItemSeqno() {
		return this.itemSeqno;
	}

	public void setItemSeqno(long itemSeqno) {
		this.itemSeqno = itemSeqno;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	/*
	 * @Column(name = "item_ytd_recpt_qty") public Integer getItemYtdRecptQty()
	 * { return this.itemYtdRecptQty; }
	 * 
	 * public void setItemYtdRecptQty(Integer itemYtdRecptQty) {
	 * this.itemYtdRecptQty = itemYtdRecptQty; }
	 */

	@Column(name = "item_ytd_issue_qty")
	public Integer getItemYtdIssueQty() {
		return this.itemYtdIssueQty;
	}

	public void setItemYtdIssueQty(Integer itemYtdIssueQty) {
		this.itemYtdIssueQty = itemYtdIssueQty;
	}

	@Column(name = "item_ytd_return_qty")
	public Integer getItemYtdReturnQty() {
		return this.itemYtdReturnQty;
	}

	public void setItemYtdReturnQty(Integer itemYtdReturnQty) {
		this.itemYtdReturnQty = itemYtdReturnQty;
	}

	@Column(name = "item_ytd_condemn_qty")
	public Integer getItemYtdCondemnQty() {
		return this.itemYtdCondemnQty;
	}

	public void setItemYtdCondemnQty(Integer itemYtdCondemnQty) {
		this.itemYtdCondemnQty = itemYtdCondemnQty;
	}

	@Column(name = "item_ytd_order_qty")
	public Integer getItemYtdOrderQty() {
		return this.itemYtdOrderQty;
	}

	public void setItemYtdOrderQty(Integer itemYtdOrderQty) {
		this.itemYtdOrderQty = itemYtdOrderQty;
	}

	@Column(name = "item_ytd_order_amt", precision = 14, scale = 4)
	public BigDecimal getItemYtdOrderAmt() {
		return this.itemYtdOrderAmt;
	}

	public void setItemYtdOrderAmt(BigDecimal itemYtdOrderAmt) {
		this.itemYtdOrderAmt = itemYtdOrderAmt;
	}

	@Column(name = "item_cum_order_amt", precision = 14, scale = 4)
	public BigDecimal getItemCumOrderAmt() {
		return this.itemCumOrderAmt;
	}

	public void setItemCumOrderAmt(BigDecimal itemCumOrderAmt) {
		this.itemCumOrderAmt = itemCumOrderAmt;
	}

	@Column(name = "create_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "update_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "item_ytd_recpt_qty_pku")
	public Integer getItemYtdRecptQtyPku() {
		return itemYtdRecptQtyPku;
	}

	public void setItemYtdRecptQtyPku(Integer itemYtdRecptQtyPku) {
		this.itemYtdRecptQtyPku = itemYtdRecptQtyPku;
	}

	@Column(name = "item_ytd_recpt_qty_sku")
	public Integer getItemYtdRecptQtySku() {
		return itemYtdRecptQtySku;
	}

	public void setItemYtdRecptQtySku(Integer itemYtdRecptQtySku) {
		this.itemYtdRecptQtySku = itemYtdRecptQtySku;
	}

	@Column(name = "item_ytd_pur_qty")
	public Integer getItemYtdPurQty() {
		return itemYtdPurQty;
	}

	public void setItemYtdPurQty(Integer itemYtdPurQty) {
		this.itemYtdPurQty = itemYtdPurQty;
	}

	@Column(name = "item_ytd_pur_amt")
	public BigDecimal getItemYtdPurAmt() {
		return itemYtdPurAmt;
	}

	public void setItemYtdPurAmt(BigDecimal itemYtdPurAmt) {
		this.itemYtdPurAmt = itemYtdPurAmt;
	}

	@Column(name = "item_ytd_recpt_amt")
	public BigDecimal getItemYtdRecptAmt() {
		return itemYtdRecptAmt;
	}

	public void setItemYtdRecptAmt(BigDecimal itemYtdRecptAmt) {
		this.itemYtdRecptAmt = itemYtdRecptAmt;
	}

}
