package my.com.cmg.iwp.maintenance.model;

// Generated Apr 19, 2012 11:10:21 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveredTo generated by hbm2java
 */
@Entity
@Table(name = "t_delivered_tos")
public class DeliveredTo implements java.io.Serializable {
	private static final long serialVersionUID = 7615413613308492125L;
	private long delToSeqno = Long.MIN_VALUE;
	private String delToCode;
	private String companyCode;
	private String locnName;
	private String remarks;
	private String regionId;
	private Long customerNo;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String delSiteDesc;
	private String delSite;
	private String address1;
	private String address2;
	private String address3;
	private String city;
	private String state;
	private String postcode;
	private String country;
	private String home_phone;
	private String mobile_phone;
	private String office_phone;
	private String fax;
	private String email;
	private String contact_person;
	private String ptjCode;
	private String ptjName;

	private Character activeFlag = 'A';

	public DeliveredTo() {
	}

	public DeliveredTo(long delToSeqno, String delToCode, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate) {
		this.delToSeqno = delToSeqno;
		this.delToCode = delToCode;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public DeliveredTo(long delToSeqno, String delToCode, String companyCode,
			String locnName, String remarks, String regionId, Long customerNo,
			String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, String address1, String address2,
			String address3, String city, String state, String postcode,
			String country, String home_phone, String mobile_phone,
			String office_phone, String fax, String email,
			String contact_person, Character activeFlag, String ptjCode,
			String ptjName) {
		this.delToSeqno = delToSeqno;
		this.delToCode = delToCode;
		this.companyCode = companyCode;
		this.locnName = locnName;
		this.remarks = remarks;
		this.regionId = regionId;
		this.customerNo = customerNo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;

		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.city = city;
		this.state = state;
		this.postcode = postcode;
		this.country = country;
		this.home_phone = home_phone;
		this.mobile_phone = mobile_phone;
		this.office_phone = office_phone;
		this.fax = fax;
		this.email = email;
		this.contact_person = contact_person;
		this.activeFlag = activeFlag;
		this.ptjCode = ptjCode;
		this.ptjName = ptjName;
	}

	@Id
	@Column(name = "del_to_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "del_to_seqno", sequenceName = "t_delivered_tos_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "del_to_seqno")
	public long getDelToSeqno() {
		return this.delToSeqno;
	}

	public void setDelToSeqno(long delToSeqno) {
		this.delToSeqno = delToSeqno;
	}

	@Column(name = "del_to_code", nullable = false, length = 20)
	public String getDelToCode() {
		return this.delToCode;
	}

	public void setDelToCode(String delToCode) {
		this.delToCode = delToCode;
	}

	@Column(name = "company_code", length = 20)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "locn_name", length = 20)
	public String getLocnName() {
		return this.locnName;
	}

	public void setLocnName(String locnName) {
		this.locnName = locnName;
	}

	@Column(name = "remarks", length = 20)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "region_id", length = 20)
	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	@Column(name = "customer_no")
	public Long getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(Long customerNo) {
		this.customerNo = customerNo;
	}

	@Column(name = "created_by", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "del_site_desc")
	public String getDelSiteDesc() {
		return delSiteDesc;
	}

	public void setDelSiteDesc(String delSiteDesc) {
		this.delSiteDesc = delSiteDesc;
	}

	@Column(name = "del_site")
	public String getDelSite() {
		return delSite;
	}

	public void setDelSite(String delSite) {
		this.delSite = delSite;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return activeFlag;
	}

	@Column(name = "address1", length = 100)
	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 100)
	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address3", length = 100)
	public String getAddress3() {
		return address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "postcode", length = 5)
	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "country", length = 48)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "home_phone", length = 10)
	public String getHomePhone() {
		return home_phone;
	}

	public void setHomePhone(String home_phone) {
		this.home_phone = home_phone;
	}

	@Column(name = "mobile_phone", length = 10)
	public String getMobilePhone() {
		return mobile_phone;
	}

	public void setMobilePhone(String mobile_phone) {
		this.mobile_phone = mobile_phone;
	}

	@Column(name = "office_phone", length = 10)
	public String getOfficePhone() {
		return office_phone;
	}

	public void setOfficePhone(String office_phone) {
		this.office_phone = office_phone;
	}

	@Column(name = "fax", length = 10)
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_person", length = 30)
	public String getContactPerson() {
		return contact_person;
	}

	public void setContactPerson(String contact_person) {
		this.contact_person = contact_person;
	}

	@Column(name = "del_tos_ptj_code", length = 20)
	public String getPtjCode() {
		return ptjCode;
	}

	public void setPtjCode(String ptjCode) {
		this.ptjCode = ptjCode;
	}

	@Column(name = "ptj_name", length = 50)
	public String getPtjName() {
		return ptjName;
	}

	public void setPtjName(String ptjName) {
		this.ptjName = ptjName;
	}

}