package my.com.cmg.iwp.maintenance.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhBudgetTransfer generated by hbm2java
 */
@Entity
@Table(name = "t_budget_transfer")
public class BudgetTransfer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3583727035991183909L;
	/**
	 * 
	 */

	private Long budgetTransferSeqno;
	private String ptjCode;
	private String facilityCodeFrom;
	private String facilityCodeTo;
	private CBMaster currentBudgetMasterByTransferFromSeqno;
	private CBMaster currentBudgetMasterByTransferToSeqno;
	private String transferNo;
	private Double transferAmount;
	private String remarks;
	private char activeFlag;
	private String parameter1;
	private String parameter2;
	private BigDecimal parameter3;
	private BigDecimal parameter4;
	private Date parameter5;
	private SecUser createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;
	private String referenceNo;
	private String transactionStatus;
	private String budgetType;
	private VoteCode voteCode;
	private VoteCode toVoteCode;
	private Integer financialYear;
	private Double fromCurrentBalance;
	private Double fromNewBalance;
	private Double toCurrentBalance;
	private Double toNewBalance;
	private String rejectremarks;
	


	@Column(name = "FROM_CURRENT_BALANCE", precision = 16, scale = 4)
	public Double getFromCurrentBalance() {
		return fromCurrentBalance;
	}

	public void setFromCurrentBalance(Double fromCurrentBalance) {
		this.fromCurrentBalance = fromCurrentBalance;
	}

	@Column(name = "FROM_NEW_BALANCE", precision = 16, scale = 4)
	public Double getFromNewBalance() {
		return fromNewBalance;
	}

	public void setFromNewBalance(Double fromNewBalance) {
		this.fromNewBalance = fromNewBalance;
	}
	
	@Column(name = "TO_CURRENT_BALANCE", precision = 16, scale = 4)
	public Double getToCurrentBalance() {
		return toCurrentBalance;
	}

	public void setToCurrentBalance(Double toCurrentBalance) {
		this.toCurrentBalance = toCurrentBalance;
	}

	@Column(name = "TO_NEW_BALANCE", precision = 16, scale = 4)
	public Double getToNewBalance() {
		return toNewBalance;
	}

	public void setToNewBalance(Double toNewBalance) {
		this.toNewBalance = toNewBalance;
	}

	@Column(name = "finacial_year")
	public Integer getFinancialYear() {
		return this.financialYear;
	}

	public void setFinancialYear(Integer financialYear) {
		this.financialYear = financialYear;
	}
	@Id
	@Column(name = "budget_transfer_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "ph_budget_transfer_seq_hq", sequenceName = "t_budget_transfer_seq", allocationSize = 1)
	@GeneratedValue(generator = "ph_budget_transfer_seq_hq")
	public Long getBudgetTransferSeqno() {
		return budgetTransferSeqno;
	}

	public void setBudgetTransferSeqno(Long budgetTransferSeqno) {
		this.budgetTransferSeqno = budgetTransferSeqno;
	}
	@Column(name = "budget_type", length = 20)
	public String getBudgetType() {
		return this.budgetType;
	}
	
	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "vote_seqno")
	public VoteCode getVoteCode() {
		return voteCode;
	}

	public void setVoteCode(VoteCode voteCode) {
		this.voteCode = voteCode;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "transfer_from_seqno")
	public CBMaster getCurrentBudgetMasterByTransferFromSeqno() {
		return this.currentBudgetMasterByTransferFromSeqno;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TO_VOTE_SEQNO")
	public VoteCode getToVoteCode() {
		return toVoteCode;
	}

	public void setToVoteCode(VoteCode toVoteCode) {
		this.toVoteCode = toVoteCode;
	}

	public void setCurrentBudgetMasterByTransferFromSeqno(
			CBMaster currentBudgetMasterByTransferFromSeqno) {
		this.currentBudgetMasterByTransferFromSeqno = currentBudgetMasterByTransferFromSeqno;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "transfer_to_seqno")
	public CBMaster getCurrentBudgetMasterByTransferToSeqno() {
		return this.currentBudgetMasterByTransferToSeqno;
	}

	public void setCurrentBudgetMasterByTransferToSeqno(
			CBMaster currentBudgetMasterByTransferToSeqno) {
		this.currentBudgetMasterByTransferToSeqno = currentBudgetMasterByTransferToSeqno;
	}

	@Column(name = "transfer_no", nullable = false, length = 20)
	public String getTransferNo() {
		return this.transferNo;
	}

	public void setTransferNo(String transferNo) {
		this.transferNo = transferNo;
	}

	@Column(name = "source_ptj_code", nullable = false, length = 20)
	public String getPtjCode() {
		return ptjCode;
	}

	public void setPtjCode(String ptjCode) {
		this.ptjCode = ptjCode;
	}

	@Column(name = "transfer_amount", precision = 16, scale = 4)
	public Double getTransferAmount() {
		return this.transferAmount;
	}

	public void setTransferAmount(Double transferAmount) {
		this.transferAmount = transferAmount;
	}

	@Column(name = "remarks", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "active_flag", nullable = false, length = 1)
	public char getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(char activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", precision = 8, scale = 4)
	public BigDecimal getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(BigDecimal parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", precision = 8, scale = 4)
	public BigDecimal getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(BigDecimal parameter4) {
		this.parameter4 = parameter4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parameter5", length = 13)
	public Date getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(Date parameter5) {
		this.parameter5 = parameter5;
	}

	@ManyToOne()
	@JoinColumn(name = "created_by")
	public SecUser getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(SecUser createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	@OrderBy
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "reference_no", length = 20)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Column(name = "facility_code", nullable = false, length = 20)
	public String getFacilityCodeFrom() {
		return facilityCodeFrom;
	}

	public void setFacilityCodeFrom(String facilityCodeFrom) {
		this.facilityCodeFrom = facilityCodeFrom;
	}
//	public String getFacilityCode() {
//		return facilityCodeFrom;
//	}
//
//	public void setFacilityCode(String facilityCodeFrom) {
//		this.facilityCodeFrom = facilityCodeFrom;
//	}

	@Column(name = "facility_codeTo", nullable = false, length = 20)
	public String getFacilityCodeTo() {
		return facilityCodeTo;
	}
	public void setFacilityCodeTo(String facilityCodeTo) {
		this.facilityCodeTo = facilityCodeTo;
	}
	
	@Column(name = "transaction_status", length = 20)
	public String getTransactionStatus() {
		return transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}
	
	@Column(name = "reject_remark", length = 500)
	public String getRejectremarks() {
		return rejectremarks;
	}

	public void setRejectremarks(String rejectremarks) {
		this.rejectremarks = rejectremarks;
	}
}
