package my.com.cmg.iwp.maintenance.model;

// Generated Apr 6, 2012 5:46:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "t_suppliers", uniqueConstraints = @UniqueConstraint(columnNames = "supplier_code"))
public class Supplier implements java.io.Serializable {
	private static final long serialVersionUID = 2874210816059787003L;
	private long sprSequenceNo = Long.MIN_VALUE;
	private String supplierCode;
	private Character activeFlag = 'A';
	private String supplierName;
	private String sprAccName;
	private String sprAccNo;
	private String sprType;
	private String sprRegNo;
	private Date sprRegExpiryDate;
	private Date sprBumiExpiryDate;
	private String sprPrincipal;
	private String sprRemarks;
	private Date createdDate;
	private long createdBy;
	private Date updatedDate;
	private long updatedBy;
	private String companyStatus;
	private String address1;
	private String address2;
	private String address3;
	private String city;
	private String state;
	private String postcode;
	private String country;
	private String homePhone;
	private String mobilePhone;
	private String officePhone;
	private String fax;
	private String email;
	private String contactPerson;
	private String companyRegNo;
	private Character defaultYn = 'N';

//	private Set<ContractHdr> contractHdr = new HashSet<ContractHdr>(0);

	public Supplier() {
	}

	public Supplier(long sprSequenceNo, String supplierCode, Date createdDate,
			long createdBy, Date updatedDate, long updatedBy) {
		this.sprSequenceNo = sprSequenceNo;
		this.supplierCode = supplierCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	public Supplier(long sprSequenceNo, String supplierCode,
			String supplierName, String sprAccName, String sprAccNo,
			String sprType, String sprRegNo, String sprRefNo,
			Date sprRegExpiryDate, String sprPrincipal, String sprRemarks,
			Date createdDate, long createdBy, Date updatedDate, long updatedBy,
			String companyStatus, String address1, String address2,
			String address3, String city, String state, String postcode,
			String country, String homePhone, String mobilePhone,
			String officePhone, String fax, String email, String contact_person, Date sprBumiExpiryDate) {
		super();
		this.sprSequenceNo = sprSequenceNo;
		this.supplierCode = supplierCode;
		this.supplierName = supplierName;
		this.sprAccName = sprAccName;
		this.sprAccNo = sprAccNo;
		this.sprType = sprType;
		this.sprRegNo = sprRegNo;
		this.sprRegExpiryDate = sprRegExpiryDate;
		this.setSprBumiExpiryDate(sprBumiExpiryDate);
		this.sprPrincipal = sprPrincipal;
		this.sprRemarks = sprRemarks;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.companyStatus = companyStatus;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.city = city;
		this.state = state;
		this.postcode = postcode;
		this.country = country;
		this.homePhone = homePhone;
		this.mobilePhone = mobilePhone;
		this.officePhone = officePhone;
		this.fax = fax;
		this.email = email;
		this.contactPerson = contact_person;
	}

	@Id
	@Column(name = "spr_seqno", unique = true, nullable = false)
	@SequenceGenerator(name = "spr_seqno", sequenceName = "t_suppliers_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "spr_seqno")
	public long getSprSequenceNo() {
		return this.sprSequenceNo;
	}

	public void setSprSequenceNo(long sprSequenceNo) {
		this.sprSequenceNo = sprSequenceNo;
	}

	@Column(name = "supplier_code", unique = true, nullable = false, length = 8)
	public String getSupplierCode() {
		return this.supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	@Column(name = "supplier_name", length = 40)
	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	@Column(name = "acc_name", length = 20)
	public String getSprAccName() {
		return this.sprAccName;
	}

	public void setSprAccName(String sprAccName) {
		this.sprAccName = sprAccName;
	}

	@Column(name = "acc_no", length = 20)
	public String getSprAccNo() {
		return this.sprAccNo;
	}

	public void setSprAccNo(String sprAccNo) {
		this.sprAccNo = sprAccNo;
	}

	@Column(name = "supplier_type", length = 1)
	public String getSprType() {
		return this.sprType;
	}

	public void setSprType(String sprType) {
		this.sprType = sprType;
	}

	@Column(name = "trs_reg_no", length = 40)
	public String getSprRegNo() {
		return this.sprRegNo;
	}

	public void setSprRegNo(String sprRegNo) {
		this.sprRegNo = sprRegNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_expiry_date", length = 29)
	public Date getSprRegExpiryDate() {
		return this.sprRegExpiryDate;
	}

	public void setSprRegExpiryDate(Date sprRegExpiryDate) {
		this.sprRegExpiryDate = sprRegExpiryDate;
	}

	@Column(name = "supplier_principal", length = 200)
	public String getSprPrincipal() {
		return this.sprPrincipal;
	}

	public void setSprPrincipal(String sprPrincipal) {
		this.sprPrincipal = sprPrincipal;
	}

	@Column(name = "remarks", length = 80)
	public String getSprRemarks() {
		return this.sprRemarks;
	}

	public void setSprRemarks(String sprRemarks) {
		this.sprRemarks = sprRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public void setCompanyStatus(String companyStatus) {
		this.companyStatus = companyStatus;
	}

	@Column(name = "company_status", length = 20)
	public String getCompanyStatus() {
		return companyStatus;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "active_flag")
	public Character getActiveFlag() {
		return activeFlag;
	}

	@Column(name = "address1", length = 100)
	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 100)
	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address3", length = 100)
	public String getAddress3() {
		return address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "postcode", length = 5)
	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "country", length = 48)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "home_phone", length = 10)
	public String getHomePhone() {
		return homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "mobile_phone", length = 10)
	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "office_phone", length = 20)
	public String getOfficePhone() {
		return officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	@Column(name = "fax", length = 10)
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_person", length = 30)
	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contact_person) {
		this.contactPerson = contact_person;
	}

	public void setDefaultYn(Character defaultYn) {
		this.defaultYn = defaultYn;
	}

	@Column(name = "default_yn")
	public Character isDefaultYn() {
		return defaultYn;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<ContractHdr> getContractHdr() {
		return contractHdr;
	}

	public void setContractHdr(Set<ContractHdr> contractHdr) {
		this.contractHdr = contractHdr;
	}*/

	public void setCompanyRegNo(String companyRegNo) {
		this.companyRegNo = companyRegNo;
	}

	@Column(name = "company_reg_no", length = 40)
	public String getCompanyRegNo() {
		return companyRegNo;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bumiputera_expiry_date", length = 29)
	public Date getSprBumiExpiryDate() {
		return sprBumiExpiryDate;
	}

	public void setSprBumiExpiryDate(Date sprBumiExpiryDate) {
		this.sprBumiExpiryDate = sprBumiExpiryDate;
	}
}